/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) H_ ## ID
#endif

#include <math.h>
#include <simstruc.h>

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* H:(q[6])->(H(q)[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][1] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a0=sin(a0);
  a5=2.2204460492503131e-16;
  a2=sin(a2);
  a6=(a5*a2);
  a7=(a0*a6);
  a4=(a4-a7);
  a7=arg[0]? arg[0][2] : 0;
  a8=cos(a7);
  a9=(a4*a8);
  a10=(a1*a2);
  a11=(a5*a3);
  a12=(a0*a11);
  a10=(a10+a12);
  a7=sin(a7);
  a12=(a10*a7);
  a13=4.4408920985006262e-16;
  a14=(a13*a7);
  a15=(a0*a14);
  a12=(a12-a15);
  a9=(a9+a12);
  a12=arg[0]? arg[0][3] : 0;
  a15=cos(a12);
  a16=(a9*a15);
  a17=(a10*a8);
  a13=(a13*a8);
  a18=(a0*a13);
  a17=(a17-a18);
  a18=(a4*a7);
  a17=(a17-a18);
  a12=sin(a12);
  a18=(a5*a12);
  a19=(a17*a18);
  a20=-4.4408920985006262e-16;
  a21=(a20*a10);
  a21=(a0-a21);
  a22=(a21*a12);
  a19=(a19-a22);
  a16=(a16+a19);
  a19=arg[0]? arg[0][4] : 0;
  a22=cos(a19);
  a23=(a16*a22);
  a24=(a5*a15);
  a25=(a17*a24);
  a26=(a21*a15);
  a25=(a25-a26);
  a26=(a9*a12);
  a25=(a25-a26);
  a19=sin(a19);
  a26=(a5*a19);
  a27=(a25*a26);
  a21=(a5*a21);
  a21=(a17+a21);
  a28=(a21*a19);
  a27=(a27+a28);
  a23=(a23+a27);
  a27=arg[0]? arg[0][5] : 0;
  a28=cos(a27);
  a29=(a23*a28);
  a30=(a5*a22);
  a31=(a25*a30);
  a32=(a21*a22);
  a31=(a31+a32);
  a16=(a16*a19);
  a31=(a31-a16);
  a27=sin(a27);
  a16=(a5*a27);
  a32=(a31*a16);
  a21=(a5*a21);
  a21=(a21-a25);
  a25=(a21*a27);
  a32=(a32+a25);
  a29=(a29+a32);
  if (res[0]!=0) res[0][0]=a29;
  a29=(a0*a3);
  a6=(a1*a6);
  a29=(a29+a6);
  a6=(a29*a8);
  a32=(a1*a14);
  a11=(a1*a11);
  a0=(a0*a2);
  a11=(a11-a0);
  a0=(a11*a7);
  a32=(a32-a0);
  a6=(a6+a32);
  a32=(a6*a15);
  a0=(a1*a13);
  a25=(a11*a8);
  a0=(a0-a25);
  a25=(a29*a7);
  a0=(a0-a25);
  a25=(a0*a18);
  a33=(a20*a11);
  a33=(a33-a1);
  a1=(a33*a12);
  a25=(a25-a1);
  a32=(a32+a25);
  a25=(a32*a22);
  a1=(a0*a24);
  a34=(a33*a15);
  a1=(a1-a34);
  a34=(a6*a12);
  a1=(a1-a34);
  a34=(a1*a26);
  a33=(a5*a33);
  a33=(a0+a33);
  a35=(a33*a19);
  a34=(a34+a35);
  a25=(a25+a34);
  a34=(a25*a28);
  a35=(a1*a30);
  a36=(a33*a22);
  a35=(a35+a36);
  a32=(a32*a19);
  a35=(a35-a32);
  a32=(a35*a16);
  a33=(a5*a33);
  a33=(a33-a1);
  a1=(a33*a27);
  a32=(a32+a1);
  a34=(a34+a32);
  if (res[0]!=0) res[0][1]=a34;
  a34=(a3*a7);
  a14=(a5*a14);
  a34=(a34+a14);
  a14=(a2*a8);
  a34=(a34-a14);
  a14=(a34*a15);
  a7=(a2*a7);
  a8=(a3*a8);
  a13=(a5*a13);
  a8=(a8+a13);
  a7=(a7+a8);
  a18=(a7*a18);
  a8=-2.2204460492503131e-16;
  a20=(a20*a3);
  a8=(a8-a20);
  a20=(a8*a12);
  a18=(a18-a20);
  a14=(a14+a18);
  a18=(a14*a22);
  a24=(a7*a24);
  a15=(a8*a15);
  a24=(a24-a15);
  a12=(a34*a12);
  a24=(a24-a12);
  a26=(a24*a26);
  a8=(a5*a8);
  a8=(a7+a8);
  a12=(a8*a19);
  a26=(a26+a12);
  a18=(a18+a26);
  a26=(a18*a28);
  a30=(a24*a30);
  a22=(a8*a22);
  a30=(a30+a22);
  a14=(a14*a19);
  a30=(a30-a14);
  a16=(a30*a16);
  a8=(a5*a8);
  a8=(a8-a24);
  a24=(a8*a27);
  a16=(a16+a24);
  a26=(a26+a16);
  if (res[0]!=0) res[0][2]=a26;
  a26=0.;
  if (res[0]!=0) res[0][3]=a26;
  a16=(a5*a28);
  a24=(a31*a16);
  a14=(a21*a28);
  a24=(a24+a14);
  a14=(a23*a27);
  a24=(a24-a14);
  if (res[0]!=0) res[0][4]=a24;
  a24=(a35*a16);
  a14=(a33*a28);
  a24=(a24+a14);
  a14=(a25*a27);
  a24=(a24-a14);
  if (res[0]!=0) res[0][5]=a24;
  a16=(a30*a16);
  a28=(a8*a28);
  a16=(a16+a28);
  a27=(a18*a27);
  a16=(a16-a27);
  if (res[0]!=0) res[0][6]=a16;
  if (res[0]!=0) res[0][7]=a26;
  a21=(a5*a21);
  a21=(a21-a31);
  if (res[0]!=0) res[0][8]=a21;
  a33=(a5*a33);
  a33=(a33-a35);
  if (res[0]!=0) res[0][9]=a33;
  a5=(a5*a8);
  a5=(a5-a30);
  if (res[0]!=0) res[0][10]=a5;
  if (res[0]!=0) res[0][11]=a26;
  a26=8.2500000000000004e-02;
  a4=(a26*a4);
  a30=-3.1600000000000000e-01;
  a10=(a30*a10);
  a4=(a4-a10);
  a10=-8.2500000000000004e-02;
  a9=(a10*a9);
  a8=3.8400000000000001e-01;
  a17=(a8*a17);
  a9=(a9+a17);
  a4=(a4+a9);
  a9=8.7999999999999995e-02;
  a23=(a9*a23);
  a4=(a4+a23);
  a23=1.0700000000000000e-01;
  a21=(a23*a21);
  a4=(a4+a21);
  if (res[0]!=0) res[0][12]=a4;
  a29=(a26*a29);
  a11=(a30*a11);
  a29=(a29+a11);
  a6=(a10*a6);
  a0=(a8*a0);
  a6=(a6+a0);
  a29=(a29+a6);
  a25=(a9*a25);
  a29=(a29+a25);
  a33=(a23*a33);
  a29=(a29+a33);
  if (res[0]!=0) res[0][13]=a29;
  a29=3.3300000000000002e-01;
  a26=(a26*a2);
  a30=(a30*a3);
  a26=(a26+a30);
  a29=(a29-a26);
  a10=(a10*a34);
  a8=(a8*a7);
  a10=(a10+a8);
  a29=(a29+a10);
  a9=(a9*a18);
  a29=(a29+a9);
  a23=(a23*a5);
  a29=(a29+a23);
  if (res[0]!=0) res[0][14]=a29;
  a29=1.;
  if (res[0]!=0) res[0][15]=a29;
  return 0;
}

CASADI_SYMBOL_EXPORT int H(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int H_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int H_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void H_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int H_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void H_release(int mem) {
}

CASADI_SYMBOL_EXPORT void H_incref(void) {
}

CASADI_SYMBOL_EXPORT void H_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int H_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int H_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real H_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* H_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* H_name_out(casadi_int i) {
  switch (i) {
    case 0: return "H(q)";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* H_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* H_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int H_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int H_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
