/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

int H(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int H_alloc_mem(void);
int H_init_mem(int mem);
void H_free_mem(int mem);
int H_checkout(void);
void H_release(int mem);
void H_incref(void);
void H_decref(void);
casadi_int H_n_in(void);
casadi_int H_n_out(void);
casadi_real H_default_in(casadi_int i);
const char* H_name_in(casadi_int i);
const char* H_name_out(casadi_int i);
const casadi_int* H_sparsity_in(casadi_int i);
const casadi_int* H_sparsity_out(casadi_int i);
int H_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int H_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define H_SZ_ARG 1
#define H_SZ_RES 1
#define H_SZ_IW 0
#define H_SZ_W 37
#ifdef __cplusplus
} /* extern "C" */
#endif
