set(UTILS_SOURCES
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/WorkspaceController.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/CasadiMPC.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/CrocoddylMPC.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/TrajectoryGenerator.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/CasadiController.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/FullSystemTorqueMapper.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/SharedMemory.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/RobotModel.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/CrocoddylController.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/CommonBaseController.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/TicToc.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/CasadiEKF.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/SignalFilter.cpp
    /home/rslstudent/Students/Emanuel/MA24_simulink/main_ros2/casadi_mpc/cpp_class_files/src/CommonBaseMPC.cpp
)
set(MPC_SOURCES
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC2_dyn_parametric_N_MPC_10.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC1_dyn_classic_N_MPC_5.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC5_kin_dev_planner_N_MPC_30.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_30.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_30.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC1_dyn_classic_N_MPC_3.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC2_dyn_parametric_N_MPC_5.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_30.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC5_kin_dev_planner_N_MPC_20.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_20.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_20.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_20.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_15.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_15.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC2_dyn_parametric_N_MPC_3.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_15.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC5_kin_dev_planner_N_MPC_10.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_10.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_10.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_10.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_5.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_5.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_5.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/fr3_ekf.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_30_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_20_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_15_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_10_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_parametric_N_MPC_5_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC2_dyn_parametric_N_MPC_10_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC2_dyn_parametric_N_MPC_5_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC2_dyn_parametric_N_MPC_3_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_30_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_20_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_15_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_10_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC3_kin_int_thelenberg_N_MPC_5_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC5_kin_dev_planner_N_MPC_30_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC5_kin_dev_planner_N_MPC_20_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC5_kin_dev_planner_N_MPC_10_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_30_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_20_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_15_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_10_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC4_kin_int_planner_N_MPC_5_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC1_dyn_classic_N_MPC_5_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/MPC1_dyn_classic_N_MPC_3_param.c
    /home/rslstudent/Students/Emanuel/MA24_simulink/s_functions/fr3_no_hand_6dof/mpc_c_sourcefiles/param_robot.c
)
