/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

int MPC3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC3_alloc_mem(void);
int MPC3_init_mem(int mem);
void MPC3_free_mem(int mem);
int MPC3_checkout(void);
void MPC3_release(int mem);
void MPC3_incref(void);
void MPC3_decref(void);
casadi_int MPC3_n_in(void);
casadi_int MPC3_n_out(void);
casadi_real MPC3_default_in(casadi_int i);
const char* MPC3_name_in(casadi_int i);
const char* MPC3_name_out(casadi_int i);
const casadi_int* MPC3_sparsity_in(casadi_int i);
const casadi_int* MPC3_sparsity_out(casadi_int i);
int MPC3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC3_SZ_ARG 23
#define MPC3_SZ_RES 15
#define MPC3_SZ_IW 0
#define MPC3_SZ_W 3195
#ifdef __cplusplus
} /* extern "C" */
#endif
