/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

int MPC14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC14_alloc_mem(void);
int MPC14_init_mem(int mem);
void MPC14_free_mem(int mem);
int MPC14_checkout(void);
void MPC14_release(int mem);
void MPC14_incref(void);
void MPC14_decref(void);
casadi_int MPC14_n_in(void);
casadi_int MPC14_n_out(void);
casadi_real MPC14_default_in(casadi_int i);
const char* MPC14_name_in(casadi_int i);
const char* MPC14_name_out(casadi_int i);
const casadi_int* MPC14_sparsity_in(casadi_int i);
const casadi_int* MPC14_sparsity_out(casadi_int i);
int MPC14_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC14_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC14_SZ_ARG 26
#define MPC14_SZ_RES 22
#define MPC14_SZ_IW 930
#define MPC14_SZ_W 13759
#ifdef __cplusplus
} /* extern "C" */
#endif
