/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC8_IW_LEN 870
#define MPC8_ARG_LEN 23
#define MPC8_RES_LEN 21
#define MPC8_W_LEN 11824
static const uint32_t MPC8_ARG[] = {0,156,432};
static const uint32_t MPC8_RES[] = {1085,1109,1385,1386,1387,1388,1389,1390,1391,1392,1393};
#define MPC8_W_END_ADDRESS 1394

// INPUT DIMENSIONS:
#define MPC8_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC8_Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define MPC8_U_PREV_LEN 30        /*u_prev: 6x5 matrix values */
#define MPC8_X_PREV_LEN 72        /*x_prev: 12x6 matrix values */
#define MPC8_U_LEN 30        /*u: 6x5 matrix values */
#define MPC8_X_LEN 72        /*x: 12x6 matrix values */
#define MPC8_LAMBDA_U_LEN 30        /*lambda_u: 6x5 matrix values */
#define MPC8_LAMBDA_X_LEN 72        /*lambda_x: 12x6 matrix values */
#define MPC8_G_LEN 72        /*g: 12x6 matrix values */
#define MPC8_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC8_Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define MPC8_R_Q_P_LEN 49        /*R_q_p: 7x7 matrix values */
#define MPC8_R_Q_PP_LEN 49        /*R_q_pp: 7x7 matrix values */
#define MPC8_R_DELTA_X1_LEN 196        /*R_delta_x1: 14x14 matrix values */
#define MPC8_R_DELTA_X_LEN 196        /*R_delta_x: 14x14 matrix values */
#define MPC8_R_DELTA_U_LEN 49        /*R_delta_u: 7x7 matrix values */
#define MPC8_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC8_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC8_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC8_U_MAX_LEN 7        /*u_max: [7 1] array values */

#define MPC8_REFERENCE_VALUES_LEN 156        /* reference_values = [x_k(12x1), y_d(7x6), u_prev(6x5), x_prev(12x6)] */
#define MPC8_INIT_GUESS_LEN 276        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define MPC8_PARAM_WEIGHT_LEN 653        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_p(7x7), R_q_pp(7x7), R_delta_x1(14x14), R_delta_x(14x14), R_delta_u(7x7), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// INPUT ADDRESSES:
#define MPC8_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC8_Y_D_ADDR 12        /*y_d: 7x6 matrix values */
#define MPC8_U_PREV_ADDR 54        /*u_prev: 6x5 matrix values */
#define MPC8_X_PREV_ADDR 84        /*x_prev: 12x6 matrix values */
#define MPC8_U_ADDR 156        /*u: 6x5 matrix values */
#define MPC8_X_ADDR 186        /*x: 12x6 matrix values */
#define MPC8_LAMBDA_U_ADDR 258        /*lambda_u: 6x5 matrix values */
#define MPC8_LAMBDA_X_ADDR 288        /*lambda_x: 12x6 matrix values */
#define MPC8_G_ADDR 360        /*g: 12x6 matrix values */
#define MPC8_Q_Y_ADDR 432        /*Q_y: 6x6 matrix values */
#define MPC8_Q_YN_ADDR 468        /*Q_yN: 6x6 matrix values */
#define MPC8_R_Q_P_ADDR 504        /*R_q_p: 7x7 matrix values */
#define MPC8_R_Q_PP_ADDR 553        /*R_q_pp: 7x7 matrix values */
#define MPC8_R_DELTA_X1_ADDR 602        /*R_delta_x1: 14x14 matrix values */
#define MPC8_R_DELTA_X_ADDR 798        /*R_delta_x: 14x14 matrix values */
#define MPC8_R_DELTA_U_ADDR 994        /*R_delta_u: 7x7 matrix values */
#define MPC8_X_MIN_ADDR 1043        /*x_min: [14 1] array values */
#define MPC8_X_MAX_ADDR 1057        /*x_max: [14 1] array values */
#define MPC8_U_MIN_ADDR 1071        /*u_min: [7 1] array values */
#define MPC8_U_MAX_ADDR 1078        /*u_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC8_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), y_d(7x6), u_prev(6x5), x_prev(12x6)] */
#define MPC8_IN_INIT_GUESS_ADDR 156        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define MPC8_IN_PARAM_WEIGHT_ADDR 432        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_p(7x7), R_q_pp(7x7), R_delta_x1(14x14), R_delta_x(14x14), R_delta_u(7x7), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC8_U_OPT_LEN 24        /*u_opt: [24 1] array values */
#define MPC8_U_OUT_LEN 30        /*u_out: 6x5 matrix values */
#define MPC8_X_OUT_LEN 72        /*x_out: 12x6 matrix values */
#define MPC8_LAMBDA_U_OUT_LEN 30        /*lambda_u_out: 6x5 matrix values */
#define MPC8_LAMBDA_X_OUT_LEN 72        /*lambda_x_out: 12x6 matrix values */
#define MPC8_G_OUT_LEN 72        /*g_out: 12x6 matrix values */
#define MPC8_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC8_J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define MPC8_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC8_J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define MPC8_J_Q_P_LEN 1        /*J_q_p: [1 1] array values */
#define MPC8_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */
#define MPC8_J_DELTA_X1_LEN 1        /*J_delta_x1: [1 1] array values */
#define MPC8_J_DELTA_X_LEN 1        /*J_delta_x: [1 1] array values */
#define MPC8_J_DELTA_U_LEN 1        /*J_delta_u: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC8_U_OPT_ADDR 1085        /*u_opt: [24 1] array values */
#define MPC8_U_OUT_ADDR 1109        /*u_out: 6x5 matrix values */
#define MPC8_X_OUT_ADDR 1139        /*x_out: 12x6 matrix values */
#define MPC8_LAMBDA_U_OUT_ADDR 1211        /*lambda_u_out: 6x5 matrix values */
#define MPC8_LAMBDA_X_OUT_ADDR 1241        /*lambda_x_out: 12x6 matrix values */
#define MPC8_G_OUT_ADDR 1313        /*g_out: 12x6 matrix values */
#define MPC8_J_YT_ADDR 1385        /*J_yt: [1 1] array values */
#define MPC8_J_YT_N_ADDR 1386        /*J_yt_N: [1 1] array values */
#define MPC8_J_YR_ADDR 1387        /*J_yr: [1 1] array values */
#define MPC8_J_YR_N_ADDR 1388        /*J_yr_N: [1 1] array values */
#define MPC8_J_Q_P_ADDR 1389        /*J_q_p: [1 1] array values */
#define MPC8_J_Q_PP_ADDR 1390        /*J_q_pp: [1 1] array values */
#define MPC8_J_DELTA_X1_ADDR 1391        /*J_delta_x1: [1 1] array values */
#define MPC8_J_DELTA_X_ADDR 1392        /*J_delta_x: [1 1] array values */
#define MPC8_J_DELTA_U_ADDR 1393        /*J_delta_u: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC8_OUT_U_OPT_ADDR 1085        /* u_opt = [u[0:11](24x1)] */
#define MPC8_OUT_INIT_GUESS_OUT_ADDR 1109        /* init_guess_out = [u_out(6x5), x_out(12x6), lambda_u_out(6x5), lambda_x_out(12x6), g_out(12x6)] */
#define MPC8_OUT_COST_FUN_1_ADDR 1385        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC8_OUT_COST_FUN_2_ADDR 1386        /* cost_fun_2 = [J_yt_N(1x1)] */
#define MPC8_OUT_COST_FUN_3_ADDR 1387        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC8_OUT_COST_FUN_4_ADDR 1388        /* cost_fun_4 = [J_yr_N(1x1)] */
#define MPC8_OUT_COST_FUN_5_ADDR 1389        /* cost_fun_5 = [J_q_p(1x1)] */
#define MPC8_OUT_COST_FUN_6_ADDR 1390        /* cost_fun_6 = [J_q_pp(1x1)] */
#define MPC8_OUT_COST_FUN_7_ADDR 1391        /* cost_fun_7 = [J_delta_x1(1x1)] */
#define MPC8_OUT_COST_FUN_8_ADDR 1392        /* cost_fun_8 = [J_delta_x(1x1)] */
#define MPC8_OUT_COST_FUN_9_ADDR 1393        /* cost_fun_9 = [J_delta_u(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
