/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

int sys_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int sys_fun_alloc_mem(void);
int sys_fun_init_mem(int mem);
void sys_fun_free_mem(int mem);
int sys_fun_checkout(void);
void sys_fun_release(int mem);
void sys_fun_incref(void);
void sys_fun_decref(void);
casadi_int sys_fun_n_in(void);
casadi_int sys_fun_n_out(void);
casadi_real sys_fun_default_in(casadi_int i);
const char* sys_fun_name_in(casadi_int i);
const char* sys_fun_name_out(casadi_int i);
const casadi_int* sys_fun_sparsity_in(casadi_int i);
const casadi_int* sys_fun_sparsity_out(casadi_int i);
int sys_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define sys_fun_SZ_ARG 3
#define sys_fun_SZ_RES 1
#define sys_fun_SZ_IW 0
#define sys_fun_SZ_W 266
#ifdef __cplusplus
} /* extern "C" */
#endif
