/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC10_IW_LEN 420
#define MPC10_ARG_LEN 23
#define MPC10_RES_LEN 17
#define MPC10_W_LEN 8022
static const uint32_t MPC10_ARG[] = {0,82,232};
static const uint32_t MPC10_RES[] = {376,382,532,533,534,535,536};
#define MPC10_W_END_ADDRESS 537

// INPUT DIMENSIONS:
#define MPC10_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC10_Y_D_LEN 70        /*y_d: 7x10 matrix values */
#define MPC10_U_LEN 6        /*u: [6 1] array values */
#define MPC10_Q_LEN 60        /*q: 6x10 matrix values */
#define MPC10_LAMBDA_U_LEN 6        /*lambda_u: [6 1] array values */
#define MPC10_LAMBDA_Q_LEN 60        /*lambda_q: 6x10 matrix values */
#define MPC10_G_LEN 24        /*g: 12x2 matrix values */
#define MPC10_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC10_Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define MPC10_R_Q_PP_LEN 36        /*R_q_pp: 6x6 matrix values */
#define MPC10_X_MIN_LEN 12        /*x_min: [12 1] array values */
#define MPC10_X_MAX_LEN 12        /*x_max: [12 1] array values */
#define MPC10_U_MIN_LEN 6        /*u_min: [6 1] array values */
#define MPC10_U_MAX_LEN 6        /*u_max: [6 1] array values */

#define MPC10_REFERENCE_VALUES_LEN 82        /* reference_values = [x_k(12x1), y_d(7x10)] */
#define MPC10_INIT_GUESS_LEN 150        /* init_guess = [u(6x1), q(6x10), lambda_u(6x1), lambda_q(6x10), g(12x2)] */
#define MPC10_PARAM_WEIGHT_LEN 144        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(6x6), x_min(12x1), x_max(12x1), u_min(6x1), u_max(6x1)] */

// INPUT ADDRESSES:
#define MPC10_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC10_Y_D_ADDR 12        /*y_d: 7x10 matrix values */
#define MPC10_U_ADDR 82        /*u: [6 1] array values */
#define MPC10_Q_ADDR 88        /*q: 6x10 matrix values */
#define MPC10_LAMBDA_U_ADDR 148        /*lambda_u: [6 1] array values */
#define MPC10_LAMBDA_Q_ADDR 154        /*lambda_q: 6x10 matrix values */
#define MPC10_G_ADDR 214        /*g: 12x2 matrix values */
#define MPC10_Q_Y_ADDR 238        /*Q_y: 6x6 matrix values */
#define MPC10_Q_YN_ADDR 274        /*Q_yN: 6x6 matrix values */
#define MPC10_R_Q_PP_ADDR 310        /*R_q_pp: 6x6 matrix values */
#define MPC10_X_MIN_ADDR 346        /*x_min: [12 1] array values */
#define MPC10_X_MAX_ADDR 358        /*x_max: [12 1] array values */
#define MPC10_U_MIN_ADDR 370        /*u_min: [6 1] array values */
#define MPC10_U_MAX_ADDR 376        /*u_max: [6 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC10_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), y_d(7x10)] */
#define MPC10_IN_INIT_GUESS_ADDR 82        /* init_guess = [u(6x1), q(6x10), lambda_u(6x1), lambda_q(6x10), g(12x2)] */
#define MPC10_IN_PARAM_WEIGHT_ADDR 232        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(6x6), x_min(12x1), x_max(12x1), u_min(6x1), u_max(6x1)] */

// OUTPUT DIMENSIONS:
#define MPC10_U_OPT_LEN 6        /*u_opt: [6 1] array values */
#define MPC10_U_OUT_LEN 6        /*u_out: [6 1] array values */
#define MPC10_Q_OUT_LEN 60        /*q_out: 6x10 matrix values */
#define MPC10_LAMBDA_U_OUT_LEN 6        /*lambda_u_out: [6 1] array values */
#define MPC10_LAMBDA_Q_OUT_LEN 60        /*lambda_q_out: 6x10 matrix values */
#define MPC10_G_OUT_LEN 24        /*g_out: 12x2 matrix values */
#define MPC10_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC10_J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define MPC10_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC10_J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define MPC10_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC10_U_OPT_ADDR 376        /*u_opt: [6 1] array values */
#define MPC10_U_OUT_ADDR 382        /*u_out: [6 1] array values */
#define MPC10_Q_OUT_ADDR 388        /*q_out: 6x10 matrix values */
#define MPC10_LAMBDA_U_OUT_ADDR 448        /*lambda_u_out: [6 1] array values */
#define MPC10_LAMBDA_Q_OUT_ADDR 454        /*lambda_q_out: 6x10 matrix values */
#define MPC10_G_OUT_ADDR 514        /*g_out: 12x2 matrix values */
#define MPC10_J_YT_ADDR 538        /*J_yt: [1 1] array values */
#define MPC10_J_YT_N_ADDR 539        /*J_yt_N: [1 1] array values */
#define MPC10_J_YR_ADDR 540        /*J_yr: [1 1] array values */
#define MPC10_J_YR_N_ADDR 541        /*J_yr_N: [1 1] array values */
#define MPC10_J_Q_PP_ADDR 542        /*J_q_pp: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC10_OUT_U_OPT_ADDR 376        /* u_opt = [u[0:5](6x1)] */
#define MPC10_OUT_INIT_GUESS_OUT_ADDR 382        /* init_guess_out = [u_out(6x1), q_out(6x10), lambda_u_out(6x1), lambda_q_out(6x10), g_out(12x2)] */
#define MPC10_OUT_COST_FUN_1_ADDR 532        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC10_OUT_COST_FUN_2_ADDR 533        /* cost_fun_2 = [J_yt_N(1x1)] */
#define MPC10_OUT_COST_FUN_3_ADDR 534        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC10_OUT_COST_FUN_4_ADDR 535        /* cost_fun_4 = [J_yr_N(1x1)] */
#define MPC10_OUT_COST_FUN_5_ADDR 536        /* cost_fun_5 = [J_q_pp(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
