/* MPC8_adressdef.h */
/* Automatically generated by MATLAB */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define IW_LEN 870
#define ARG_LEN 23
#define RES_LEN 17
#define W_LEN 9606
static const uint32_t ARG[] = {0,54,330};
static const uint32_t RES[] = {510,516,792,793,794,795,796};
#define W_END_ADDRESS 797

#endif /* MPC8_ADRESSDEF_H */
