/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC8_IW_LEN 870
#define MPC8_ARG_LEN 23
#define MPC8_RES_LEN 17
#define MPC8_W_LEN 9606
static const uint32_t MPC8_ARG[] = {0,54,330};
static const uint32_t MPC8_RES[] = {510,516,792,794,795,796};
#define MPC8_W_END_ADDRESS 797

// INPUT DIMENSIONS:
#define X_K_LEN 12        /*x_k: [12 1] array values */
#define Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define U_LEN 30        /*u: 6x5 matrix values */
#define X_LEN 72        /*x: 12x6 matrix values */
#define LAMBDA_U_LEN 30        /*lambda_u: 6x5 matrix values */
#define LAMBDA_X_LEN 72        /*lambda_x: 12x6 matrix values */
#define G_LEN 72        /*g: 12x6 matrix values */
#define Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define Q_YKP1_LEN 36        /*Q_ykp1: 6x6 matrix values */
#define Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define R_Q_PP_LEN 36        /*R_q_pp: 6x6 matrix values */
#define X_MIN_LEN 12        /*x_min: [12 1] array values */
#define X_MAX_LEN 12        /*x_max: [12 1] array values */
#define U_MIN_LEN 6        /*u_min: [6 1] array values */
#define U_MAX_LEN 6        /*u_max: [6 1] array values */

// INPUT ADDRESSES:
#define REFERENCE_VALUES_LEN 54        /* reference_values = [x_k(12x1), y_d(7x6)] */
#define INIT_GUESS_LEN 276        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define PARAM_WEIGHT_LEN 180        /* param_weight = [Q_y(6x6), Q_ykp1(6x6), Q_yN(6x6), R_q_pp(6x6), x_min(12x1), x_max(12x1), u_min(6x1), u_max(6x1)] */
#define X_K_ADDR 0        /*x_k: [12 1] array values */
#define Y_D_ADDR 12        /*y_d: 7x6 matrix values */
#define U_ADDR 54        /*u: 6x5 matrix values */
#define X_ADDR 84        /*x: 12x6 matrix values */
#define LAMBDA_U_ADDR 156        /*lambda_u: 6x5 matrix values */
#define LAMBDA_X_ADDR 186        /*lambda_x: 12x6 matrix values */
#define G_ADDR 258        /*g: 12x6 matrix values */
#define Q_Y_ADDR 330        /*Q_y: 6x6 matrix values */
#define Q_YKP1_ADDR 366        /*Q_ykp1: 6x6 matrix values */
#define Q_YN_ADDR 402        /*Q_yN: 6x6 matrix values */
#define R_Q_PP_ADDR 438        /*R_q_pp: 6x6 matrix values */
#define X_MIN_ADDR 474        /*x_min: [12 1] array values */
#define X_MAX_ADDR 486        /*x_max: [12 1] array values */
#define U_MIN_ADDR 498        /*u_min: [6 1] array values */
#define U_MAX_ADDR 504        /*u_max: [6 1] array values */

#define REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), y_d(7x6)] */
#define INIT_GUESS_ADDR 54        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define PARAM_WEIGHT_ADDR 330        /* param_weight = [Q_y(6x6), Q_ykp1(6x6), Q_yN(6x6), R_q_pp(6x6), x_min(12x1), x_max(12x1), u_min(6x1), u_max(6x1)] */

// OUTPUT DIMENSIONS:
#define U_OPT_LEN 6        /*u_opt: [6 1] array values */
#define U_OUT_LEN 30        /*u_out: 6x5 matrix values */
#define X_OUT_LEN 72        /*x_out: 12x6 matrix values */
#define LAMBDA_U_OUT_LEN 30        /*lambda_u_out: 6x5 matrix values */
#define LAMBDA_X_OUT_LEN 72        /*lambda_x_out: 12x6 matrix values */
#define G_OUT_LEN 72        /*g_out: 12x6 matrix values */
#define J_YT_LEN 1        /*J_yt: [1 1] array values */
#define J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define J_YR_LEN 1        /*J_yr: [1 1] array values */
#define J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */

// OUTPUT ADDRESSES:
#define U_OPT_ADDR 510        /*u_opt: [6 1] array values */
#define U_OUT_ADDR 516        /*u_out: 6x5 matrix values */
#define X_OUT_ADDR 546        /*x_out: 12x6 matrix values */
#define LAMBDA_U_OUT_ADDR 618        /*lambda_u_out: 6x5 matrix values */
#define LAMBDA_X_OUT_ADDR 648        /*lambda_x_out: 12x6 matrix values */
#define G_OUT_ADDR 720        /*g_out: 12x6 matrix values */
#define J_YT_ADDR 792        /*J_yt: [1 1] array values */
#define J_YT_N_ADDR 793        /*J_yt_N: [1 1] array values */
#define J_YR_ADDR 794        /*J_yr: [1 1] array values */
#define J_YR_N_ADDR 795        /*J_yr_N: [1 1] array values */
#define J_Q_PP_ADDR 796        /*J_q_pp: [1 1] array values */

#endif /* MPC8_ADRESSDEF_H */
