controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    gravity_compensation_example_controller:
      type: franka_example_controllers/GravityCompensationExampleController
      
    mpc_crocoddyl_controller:
      type: franka_example_controllers/ModelPredictiveControllerCrocoddyl
      
    mpc_crocoddyl_controller_shm:
      type: franka_example_controllers/ModelPredictiveControllerCrocoddylSHM
      
    mpc_casadi_controller:
      type: franka_example_controllers/ModelPredictiveControllerCasadi

    conventional_workspace_controller:
      type: conventional_workspace_controller/ConventionalWorkspaceController

    move_to_start_example_controller:
      type: franka_example_controllers/MoveToStartExampleController

move_to_start_example_controller:
  ros__parameters:
    arm_id: panda
    k_gains:
      - 600.0
      - 600.0
      - 600.0
      - 600.0
      - 250.0
      - 150.0
      - 50.0
    d_gains:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 10.0
      - 10.0
      - 5.
