controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_rate_limiter: true
    cutoff_frequency: 1000

    gravity_compensation_example_controller:
      type: franka_example_controllers/GravityCompensationExampleController
      
    mpc_crocoddyl_controller:
      type: franka_example_controllers/ModelPredictiveControllerCrocoddyl
      
    mpc_crocoddyl_controller_shm_controller:
      type: franka_example_controllers/ModelPredictiveControllerCrocoddylSHMController

    mpc_crocoddyl_controller_shm:
      type: franka_example_controllers/ModelPredictiveControllerCrocoddylSHM
      
    mpc_casadi_controller:
      type: franka_example_controllers/ModelPredictiveControllerCasadi

    conventional_workspace_controller:
      type: conventional_workspace_controller/ConventionalWorkspaceController

    move_to_start_example_controller:
      type: franka_example_controllers/MoveToStartExampleController

move_to_start_example_controller:
  ros__parameters:
    arm_id: panda
    k_gains:
      - 2000.0
      - 2000.0
      - 2000.0
      - 2000.0
      - 500.0
      - 300.0
      - 100.0
    d_gains:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 10.0
      - 10.0
      - 5.
    enable_single_joint_homing: true
    trajectory_selection: 1
