/* Automatically generated by MATLAB (generate_casadi_types.m) */
/* Do not edit this file. To regenerate, run "mpc_casdadi_main.m" with "generate_realtime_udp_c_fun=true" */

#ifndef casadi_types_H
#define casadi_types_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef Inf
#define Inf INFINITY
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

typedef int (*CasadiFunPtr_t)(const casadi_real **arg, casadi_real **res, casadi_int *iw, casadi_real *w, int mem);

#ifdef __cplusplus
}
#endif

#endif // casadi_types_H
