/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC01_IW_LEN 870
#define MPC01_ARG_LEN 23
#define MPC01_RES_LEN 20
#define MPC01_W_LEN 19036
static const uint32_t MPC01_ARG[] = {0,156,432};
static const uint32_t MPC01_RES[] = {1036,1042,1318,1319,1320,1321,1322,1323,1324,1325};
#define MPC01_W_END_ADDRESS 1326

// INPUT DIMENSIONS:
#define MPC01_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC01_Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define MPC01_U_PREV_LEN 30        /*u_prev: 6x5 matrix values */
#define MPC01_X_PREV_LEN 72        /*x_prev: 12x6 matrix values */
#define MPC01_U_LEN 30        /*u: 6x5 matrix values */
#define MPC01_X_LEN 72        /*x: 12x6 matrix values */
#define MPC01_LAMBDA_U_LEN 30        /*lambda_u: 6x5 matrix values */
#define MPC01_LAMBDA_X_LEN 72        /*lambda_x: 12x6 matrix values */
#define MPC01_G_LEN 72        /*g: 12x6 matrix values */
#define MPC01_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC01_Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define MPC01_R_U0_LEN 49        /*R_u0: 7x7 matrix values */
#define MPC01_R_U_LEN 49        /*R_u: 7x7 matrix values */
#define MPC01_R_X0_LEN 196        /*R_x0: 14x14 matrix values */
#define MPC01_R_X_LEN 196        /*R_x: 14x14 matrix values */
#define MPC01_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC01_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC01_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC01_U_MAX_LEN 7        /*u_max: [7 1] array values */

#define MPC01_REFERENCE_VALUES_LEN 156        /* reference_values = [x_k(12x1), y_d(7x6), u_prev(6x5), x_prev(12x6)] */
#define MPC01_INIT_GUESS_LEN 276        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define MPC01_PARAM_WEIGHT_LEN 604        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_u0(7x7), R_u(7x7), R_x0(14x14), R_x(14x14), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// INPUT ADDRESSES:
#define MPC01_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC01_Y_D_ADDR 12        /*y_d: 7x6 matrix values */
#define MPC01_U_PREV_ADDR 54        /*u_prev: 6x5 matrix values */
#define MPC01_X_PREV_ADDR 84        /*x_prev: 12x6 matrix values */
#define MPC01_U_ADDR 156        /*u: 6x5 matrix values */
#define MPC01_X_ADDR 186        /*x: 12x6 matrix values */
#define MPC01_LAMBDA_U_ADDR 258        /*lambda_u: 6x5 matrix values */
#define MPC01_LAMBDA_X_ADDR 288        /*lambda_x: 12x6 matrix values */
#define MPC01_G_ADDR 360        /*g: 12x6 matrix values */
#define MPC01_Q_Y_ADDR 432        /*Q_y: 6x6 matrix values */
#define MPC01_Q_YN_ADDR 468        /*Q_yN: 6x6 matrix values */
#define MPC01_R_U0_ADDR 504        /*R_u0: 7x7 matrix values */
#define MPC01_R_U_ADDR 553        /*R_u: 7x7 matrix values */
#define MPC01_R_X0_ADDR 602        /*R_x0: 14x14 matrix values */
#define MPC01_R_X_ADDR 798        /*R_x: 14x14 matrix values */
#define MPC01_X_MIN_ADDR 994        /*x_min: [14 1] array values */
#define MPC01_X_MAX_ADDR 1008        /*x_max: [14 1] array values */
#define MPC01_U_MIN_ADDR 1022        /*u_min: [7 1] array values */
#define MPC01_U_MAX_ADDR 1029        /*u_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC01_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), y_d(7x6), u_prev(6x5), x_prev(12x6)] */
#define MPC01_IN_INIT_GUESS_ADDR 156        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define MPC01_IN_PARAM_WEIGHT_ADDR 432        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_u0(7x7), R_u(7x7), R_x0(14x14), R_x(14x14), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC01_U_OPT_LEN 6        /*u_opt: [6 1] array values */
#define MPC01_U_OUT_LEN 30        /*u_out: 6x5 matrix values */
#define MPC01_X_OUT_LEN 72        /*x_out: 12x6 matrix values */
#define MPC01_LAMBDA_U_OUT_LEN 30        /*lambda_u_out: 6x5 matrix values */
#define MPC01_LAMBDA_X_OUT_LEN 72        /*lambda_x_out: 12x6 matrix values */
#define MPC01_G_OUT_LEN 72        /*g_out: 12x6 matrix values */
#define MPC01_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC01_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC01_J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define MPC01_J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define MPC01_J_U_LEN 1        /*J_u: [1 1] array values */
#define MPC01_J_X_LEN 1        /*J_x: [1 1] array values */
#define MPC01_J_U0_LEN 1        /*J_u0: [1 1] array values */
#define MPC01_J_X0_LEN 1        /*J_x0: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC01_U_OPT_ADDR 1036        /*u_opt: [6 1] array values */
#define MPC01_U_OUT_ADDR 1042        /*u_out: 6x5 matrix values */
#define MPC01_X_OUT_ADDR 1072        /*x_out: 12x6 matrix values */
#define MPC01_LAMBDA_U_OUT_ADDR 1144        /*lambda_u_out: 6x5 matrix values */
#define MPC01_LAMBDA_X_OUT_ADDR 1174        /*lambda_x_out: 12x6 matrix values */
#define MPC01_G_OUT_ADDR 1246        /*g_out: 12x6 matrix values */
#define MPC01_J_YT_ADDR 1318        /*J_yt: [1 1] array values */
#define MPC01_J_YR_ADDR 1319        /*J_yr: [1 1] array values */
#define MPC01_J_YT_N_ADDR 1320        /*J_yt_N: [1 1] array values */
#define MPC01_J_YR_N_ADDR 1321        /*J_yr_N: [1 1] array values */
#define MPC01_J_U_ADDR 1322        /*J_u: [1 1] array values */
#define MPC01_J_X_ADDR 1323        /*J_x: [1 1] array values */
#define MPC01_J_U0_ADDR 1324        /*J_u0: [1 1] array values */
#define MPC01_J_X0_ADDR 1325        /*J_x0: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC01_OUT_U_OPT_ADDR 1036        /* u_opt = [u[0:5](6x1)] */
#define MPC01_OUT_INIT_GUESS_OUT_ADDR 1042        /* init_guess_out = [u_out(6x5), x_out(12x6), lambda_u_out(6x5), lambda_x_out(12x6), g_out(12x6)] */
#define MPC01_OUT_COST_FUN_1_ADDR 1318        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC01_OUT_COST_FUN_2_ADDR 1319        /* cost_fun_2 = [J_yr(1x1)] */
#define MPC01_OUT_COST_FUN_3_ADDR 1320        /* cost_fun_3 = [J_yt_N(1x1)] */
#define MPC01_OUT_COST_FUN_4_ADDR 1321        /* cost_fun_4 = [J_yr_N(1x1)] */
#define MPC01_OUT_COST_FUN_5_ADDR 1322        /* cost_fun_5 = [J_u(1x1)] */
#define MPC01_OUT_COST_FUN_6_ADDR 1323        /* cost_fun_6 = [J_x(1x1)] */
#define MPC01_OUT_COST_FUN_7_ADDR 1324        /* cost_fun_7 = [J_u0(1x1)] */
#define MPC01_OUT_COST_FUN_8_ADDR 1325        /* cost_fun_8 = [J_x0(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
