/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC01(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC01_alloc_mem(void);
int MPC01_init_mem(int mem);
void MPC01_free_mem(int mem);
int MPC01_checkout(void);
void MPC01_release(int mem);
void MPC01_incref(void);
void MPC01_decref(void);
casadi_int MPC01_n_in(void);
casadi_int MPC01_n_out(void);
casadi_real MPC01_default_in(casadi_int i);
const char* MPC01_name_in(casadi_int i);
const char* MPC01_name_out(casadi_int i);
const casadi_int* MPC01_sparsity_in(casadi_int i);
const casadi_int* MPC01_sparsity_out(casadi_int i);
int MPC01_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC01_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC01_SZ_ARG 23
#define MPC01_SZ_RES 17
#define MPC01_SZ_IW 290
#define MPC01_SZ_W 3611
#ifdef __cplusplus
} /* extern "C" */
#endif
