/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC12_alloc_mem(void);
int MPC12_init_mem(int mem);
void MPC12_free_mem(int mem);
int MPC12_checkout(void);
void MPC12_release(int mem);
void MPC12_incref(void);
void MPC12_decref(void);
casadi_int MPC12_n_in(void);
casadi_int MPC12_n_out(void);
casadi_real MPC12_default_in(casadi_int i);
const char* MPC12_name_in(casadi_int i);
const char* MPC12_name_out(casadi_int i);
const casadi_int* MPC12_sparsity_in(casadi_int i);
const casadi_int* MPC12_sparsity_out(casadi_int i);
int MPC12_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC12_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC12_SZ_ARG 23
#define MPC12_SZ_RES 17
#define MPC12_SZ_IW 290
#define MPC12_SZ_W 2899
#ifdef __cplusplus
} /* extern "C" */
#endif
