/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC12_IW_LEN 1015
#define MPC12_ARG_LEN 23
#define MPC12_RES_LEN 17
#define MPC12_W_LEN 12474
static const uint32_t MPC12_ARG[] = {0,56,378};
static const uint32_t MPC12_RES[] = {541,576,898,899,900,901,902};
#define MPC12_W_END_ADDRESS 903

// INPUT DIMENSIONS:
#define MPC12_X_K_LEN 14        /*x_k: [14 1] array values */
#define MPC12_Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define MPC12_U_LEN 35        /*u: 7x5 matrix values */
#define MPC12_X_LEN 84        /*x: 14x6 matrix values */
#define MPC12_LAMBDA_U_LEN 35        /*lambda_u: 7x5 matrix values */
#define MPC12_LAMBDA_X_LEN 84        /*lambda_x: 14x6 matrix values */
#define MPC12_G_LEN 84        /*g: 14x6 matrix values */
#define MPC12_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC12_Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define MPC12_R_Q_PP_LEN 49        /*R_q_pp: 7x7 matrix values */
#define MPC12_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC12_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC12_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC12_U_MAX_LEN 7        /*u_max: [7 1] array values */

#define MPC12_REFERENCE_VALUES_LEN 56        /* reference_values = [x_k(14x1), y_d(7x6)] */
#define MPC12_INIT_GUESS_LEN 322        /* init_guess = [u(7x5), x(14x6), lambda_u(7x5), lambda_x(14x6), g(14x6)] */
#define MPC12_PARAM_WEIGHT_LEN 163        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(7x7), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// INPUT ADDRESSES:
#define MPC12_X_K_ADDR 0        /*x_k: [14 1] array values */
#define MPC12_Y_D_ADDR 14        /*y_d: 7x6 matrix values */
#define MPC12_U_ADDR 56        /*u: 7x5 matrix values */
#define MPC12_X_ADDR 91        /*x: 14x6 matrix values */
#define MPC12_LAMBDA_U_ADDR 175        /*lambda_u: 7x5 matrix values */
#define MPC12_LAMBDA_X_ADDR 210        /*lambda_x: 14x6 matrix values */
#define MPC12_G_ADDR 294        /*g: 14x6 matrix values */
#define MPC12_Q_Y_ADDR 378        /*Q_y: 6x6 matrix values */
#define MPC12_Q_YN_ADDR 414        /*Q_yN: 6x6 matrix values */
#define MPC12_R_Q_PP_ADDR 450        /*R_q_pp: 7x7 matrix values */
#define MPC12_X_MIN_ADDR 499        /*x_min: [14 1] array values */
#define MPC12_X_MAX_ADDR 513        /*x_max: [14 1] array values */
#define MPC12_U_MIN_ADDR 527        /*u_min: [7 1] array values */
#define MPC12_U_MAX_ADDR 534        /*u_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC12_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(14x1), y_d(7x6)] */
#define MPC12_IN_INIT_GUESS_ADDR 56        /* init_guess = [u(7x5), x(14x6), lambda_u(7x5), lambda_x(14x6), g(14x6)] */
#define MPC12_IN_PARAM_WEIGHT_ADDR 378        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(7x7), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC12_U_OPT_LEN 35        /*u_opt: [35 1] array values */
#define MPC12_U_OUT_LEN 35        /*u_out: 7x5 matrix values */
#define MPC12_X_OUT_LEN 84        /*x_out: 14x6 matrix values */
#define MPC12_LAMBDA_U_OUT_LEN 35        /*lambda_u_out: 7x5 matrix values */
#define MPC12_LAMBDA_X_OUT_LEN 84        /*lambda_x_out: 14x6 matrix values */
#define MPC12_G_OUT_LEN 84        /*g_out: 14x6 matrix values */
#define MPC12_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC12_J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define MPC12_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC12_J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define MPC12_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC12_U_OPT_ADDR 541        /*u_opt: [35 1] array values */
#define MPC12_U_OUT_ADDR 576        /*u_out: 7x5 matrix values */
#define MPC12_X_OUT_ADDR 611        /*x_out: 14x6 matrix values */
#define MPC12_LAMBDA_U_OUT_ADDR 695        /*lambda_u_out: 7x5 matrix values */
#define MPC12_LAMBDA_X_OUT_ADDR 730        /*lambda_x_out: 14x6 matrix values */
#define MPC12_G_OUT_ADDR 814        /*g_out: 14x6 matrix values */
#define MPC12_J_YT_ADDR 898        /*J_yt: [1 1] array values */
#define MPC12_J_YT_N_ADDR 899        /*J_yt_N: [1 1] array values */
#define MPC12_J_YR_ADDR 900        /*J_yr: [1 1] array values */
#define MPC12_J_YR_N_ADDR 901        /*J_yr_N: [1 1] array values */
#define MPC12_J_Q_PP_ADDR 902        /*J_q_pp: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC12_OUT_U_OPT_ADDR 541        /* u_opt = [x[0:27](35x1)] */
#define MPC12_OUT_INIT_GUESS_OUT_ADDR 576        /* init_guess_out = [u_out(7x5), x_out(14x6), lambda_u_out(7x5), lambda_x_out(14x6), g_out(14x6)] */
#define MPC12_OUT_COST_FUN_1_ADDR 898        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC12_OUT_COST_FUN_2_ADDR 899        /* cost_fun_2 = [J_yt_N(1x1)] */
#define MPC12_OUT_COST_FUN_3_ADDR 900        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC12_OUT_COST_FUN_4_ADDR 901        /* cost_fun_4 = [J_yr_N(1x1)] */
#define MPC12_OUT_COST_FUN_5_ADDR 902        /* cost_fun_5 = [J_q_pp(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
