/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC10_IW_LEN 300
#define MPC10_ARG_LEN 23
#define MPC10_RES_LEN 19
#define MPC10_W_LEN 6195
static const uint32_t MPC10_ARG[] = {0,90,192};
static const uint32_t MPC10_RES[] = {747,753,855,856,857,858,859,860,861};
#define MPC10_W_END_ADDRESS 862

// INPUT DIMENSIONS:
#define MPC10_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC10_Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define MPC10_Q_PREV_LEN 36        /*q_prev: 6x6 matrix values */
#define MPC10_U_LEN 6        /*u: [6 1] array values */
#define MPC10_Q_LEN 36        /*q: 6x6 matrix values */
#define MPC10_LAMBDA_U_LEN 6        /*lambda_u: [6 1] array values */
#define MPC10_LAMBDA_Q_LEN 36        /*lambda_q: 6x6 matrix values */
#define MPC10_G_LEN 24        /*g: 12x2 matrix values */
#define MPC10_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC10_Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define MPC10_R_Q_PP_LEN 49        /*R_q_pp: 7x7 matrix values */
#define MPC10_R_X0_LEN 196        /*R_x0: 14x14 matrix values */
#define MPC10_R_X_LEN 196        /*R_x: 14x14 matrix values */
#define MPC10_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC10_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC10_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC10_U_MAX_LEN 7        /*u_max: [7 1] array values */

#define MPC10_REFERENCE_VALUES_LEN 90        /* reference_values = [x_k(12x1), y_d(7x6), q_prev(6x6)] */
#define MPC10_INIT_GUESS_LEN 102        /* init_guess = [u(6x1), q(6x6), lambda_u(6x1), lambda_q(6x6), g(12x2)] */
#define MPC10_PARAM_WEIGHT_LEN 555        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(7x7), R_x0(14x14), R_x(14x14), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// INPUT ADDRESSES:
#define MPC10_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC10_Y_D_ADDR 12        /*y_d: 7x6 matrix values */
#define MPC10_Q_PREV_ADDR 54        /*q_prev: 6x6 matrix values */
#define MPC10_U_ADDR 90        /*u: [6 1] array values */
#define MPC10_Q_ADDR 96        /*q: 6x6 matrix values */
#define MPC10_LAMBDA_U_ADDR 132        /*lambda_u: [6 1] array values */
#define MPC10_LAMBDA_Q_ADDR 138        /*lambda_q: 6x6 matrix values */
#define MPC10_G_ADDR 174        /*g: 12x2 matrix values */
#define MPC10_Q_Y_ADDR 198        /*Q_y: 6x6 matrix values */
#define MPC10_Q_YN_ADDR 234        /*Q_yN: 6x6 matrix values */
#define MPC10_R_Q_PP_ADDR 270        /*R_q_pp: 7x7 matrix values */
#define MPC10_R_X0_ADDR 319        /*R_x0: 14x14 matrix values */
#define MPC10_R_X_ADDR 515        /*R_x: 14x14 matrix values */
#define MPC10_X_MIN_ADDR 711        /*x_min: [14 1] array values */
#define MPC10_X_MAX_ADDR 725        /*x_max: [14 1] array values */
#define MPC10_U_MIN_ADDR 739        /*u_min: [7 1] array values */
#define MPC10_U_MAX_ADDR 746        /*u_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC10_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), y_d(7x6), q_prev(6x6)] */
#define MPC10_IN_INIT_GUESS_ADDR 90        /* init_guess = [u(6x1), q(6x6), lambda_u(6x1), lambda_q(6x6), g(12x2)] */
#define MPC10_IN_PARAM_WEIGHT_ADDR 192        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(7x7), R_x0(14x14), R_x(14x14), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC10_U_OPT_LEN 6        /*u_opt: [6 1] array values */
#define MPC10_U_OUT_LEN 6        /*u_out: [6 1] array values */
#define MPC10_Q_OUT_LEN 36        /*q_out: 6x6 matrix values */
#define MPC10_LAMBDA_U_OUT_LEN 6        /*lambda_u_out: [6 1] array values */
#define MPC10_LAMBDA_Q_OUT_LEN 36        /*lambda_q_out: 6x6 matrix values */
#define MPC10_G_OUT_LEN 24        /*g_out: 12x2 matrix values */
#define MPC10_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC10_J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define MPC10_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC10_J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define MPC10_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */
#define MPC10_J_X_LEN 1        /*J_x: [1 1] array values */
#define MPC10_J_X0_LEN 1        /*J_x0: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC10_U_OPT_ADDR 747        /*u_opt: [6 1] array values */
#define MPC10_U_OUT_ADDR 753        /*u_out: [6 1] array values */
#define MPC10_Q_OUT_ADDR 759        /*q_out: 6x6 matrix values */
#define MPC10_LAMBDA_U_OUT_ADDR 795        /*lambda_u_out: [6 1] array values */
#define MPC10_LAMBDA_Q_OUT_ADDR 801        /*lambda_q_out: 6x6 matrix values */
#define MPC10_G_OUT_ADDR 837        /*g_out: 12x2 matrix values */
#define MPC10_J_YT_ADDR 861        /*J_yt: [1 1] array values */
#define MPC10_J_YT_N_ADDR 862        /*J_yt_N: [1 1] array values */
#define MPC10_J_YR_ADDR 863        /*J_yr: [1 1] array values */
#define MPC10_J_YR_N_ADDR 864        /*J_yr_N: [1 1] array values */
#define MPC10_J_Q_PP_ADDR 865        /*J_q_pp: [1 1] array values */
#define MPC10_J_X_ADDR 866        /*J_x: [1 1] array values */
#define MPC10_J_X0_ADDR 867        /*J_x0: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC10_OUT_U_OPT_ADDR 747        /* u_opt = [u[0:5](6x1)] */
#define MPC10_OUT_INIT_GUESS_OUT_ADDR 753        /* init_guess_out = [u_out(6x1), q_out(6x6), lambda_u_out(6x1), lambda_q_out(6x6), g_out(12x2)] */
#define MPC10_OUT_COST_FUN_1_ADDR 855        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC10_OUT_COST_FUN_2_ADDR 856        /* cost_fun_2 = [J_yt_N(1x1)] */
#define MPC10_OUT_COST_FUN_3_ADDR 857        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC10_OUT_COST_FUN_4_ADDR 858        /* cost_fun_4 = [J_yr_N(1x1)] */
#define MPC10_OUT_COST_FUN_5_ADDR 859        /* cost_fun_5 = [J_q_pp(1x1)] */
#define MPC10_OUT_COST_FUN_6_ADDR 860        /* cost_fun_6 = [J_x(1x1)] */
#define MPC10_OUT_COST_FUN_7_ADDR 861        /* cost_fun_7 = [J_x0(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
