/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC13_alloc_mem(void);
int MPC13_init_mem(int mem);
void MPC13_free_mem(int mem);
int MPC13_checkout(void);
void MPC13_release(int mem);
void MPC13_incref(void);
void MPC13_decref(void);
casadi_int MPC13_n_in(void);
casadi_int MPC13_n_out(void);
casadi_real MPC13_default_in(casadi_int i);
const char* MPC13_name_in(casadi_int i);
const char* MPC13_name_out(casadi_int i);
const casadi_int* MPC13_sparsity_in(casadi_int i);
const casadi_int* MPC13_sparsity_out(casadi_int i);
int MPC13_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC13_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC13_SZ_ARG 23
#define MPC13_SZ_RES 17
#define MPC13_SZ_IW 490
#define MPC13_SZ_W 6734
#ifdef __cplusplus
} /* extern "C" */
#endif
