/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC10_alloc_mem(void);
int MPC10_init_mem(int mem);
void MPC10_free_mem(int mem);
int MPC10_checkout(void);
void MPC10_release(int mem);
void MPC10_incref(void);
void MPC10_decref(void);
casadi_int MPC10_n_in(void);
casadi_int MPC10_n_out(void);
casadi_real MPC10_default_in(casadi_int i);
const char* MPC10_name_in(casadi_int i);
const char* MPC10_name_out(casadi_int i);
const casadi_int* MPC10_sparsity_in(casadi_int i);
const casadi_int* MPC10_sparsity_out(casadi_int i);
int MPC10_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC10_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC10_SZ_ARG 23
#define MPC10_SZ_RES 19
#define MPC10_SZ_IW 900
#define MPC10_SZ_W 12725
#ifdef __cplusplus
} /* extern "C" */
#endif
