/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC11_IW_LEN 320
#define MPC11_ARG_LEN 23
#define MPC11_RES_LEN 19
#define MPC11_W_LEN 3577
static const uint32_t MPC11_ARG[] = {0,5,109};
static const uint32_t MPC11_RES[] = {275,277,381,382,383,384,385,386,387};
#define MPC11_W_END_ADDRESS 388

// INPUT DIMENSIONS:
#define MPC11_X_K_LEN 4        /*x_k: [4 1] array values */
#define MPC11_T_LEN 1        /*t: [1 1] array values */
#define MPC11_U_LEN 10        /*u: 2x5 matrix values */
#define MPC11_X_LEN 24        /*x: 4x6 matrix values */
#define MPC11_THETA_LEN 6        /*theta: [1 6] array values */
#define MPC11_LAMBDA_U_LEN 10        /*lambda_u: 2x5 matrix values */
#define MPC11_LAMBDA_X_LEN 24        /*lambda_x: 4x6 matrix values */
#define MPC11_LAMBDA_THETA_LEN 6        /*lambda_theta: [1 6] array values */
#define MPC11_G_LEN 24        /*g: 4x6 matrix values */
#define MPC11_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC11_Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define MPC11_Q_LEN 1        /*Q: [1 1] array values */
#define MPC11_Q_LEN 1        /*Q: [1 1] array values */
#define MPC11_LAMBDA_LEN 1        /*lambda: [1 1] array values */
#define MPC11_R_Q_PP_LEN 49        /*R_q_pp: 7x7 matrix values */
#define MPC11_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC11_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC11_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC11_U_MAX_LEN 7        /*u_max: [7 1] array values */

#define MPC11_REFERENCE_VALUES_LEN 5        /* reference_values = [x_k(4x1), t(1x1)] */
#define MPC11_INIT_GUESS_LEN 104        /* init_guess = [u(2x5), x(4x6), theta(1x6), lambda_u(2x5), lambda_x(4x6), lambda_theta(1x6), g(4x6)] */
#define MPC11_PARAM_WEIGHT_LEN 166        /* param_weight = [Q_y(6x6), Q_yN(6x6), Q(1x1), Q(1x1), lambda(1x1), R_q_pp(7x7), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// INPUT ADDRESSES:
#define MPC11_X_K_ADDR 0        /*x_k: [4 1] array values */
#define MPC11_T_ADDR 4        /*t: [1 1] array values */
#define MPC11_U_ADDR 5        /*u: 2x5 matrix values */
#define MPC11_X_ADDR 15        /*x: 4x6 matrix values */
#define MPC11_THETA_ADDR 39        /*theta: [1 6] array values */
#define MPC11_LAMBDA_U_ADDR 45        /*lambda_u: 2x5 matrix values */
#define MPC11_LAMBDA_X_ADDR 55        /*lambda_x: 4x6 matrix values */
#define MPC11_LAMBDA_THETA_ADDR 79        /*lambda_theta: [1 6] array values */
#define MPC11_G_ADDR 85        /*g: 4x6 matrix values */
#define MPC11_Q_Y_ADDR 109        /*Q_y: 6x6 matrix values */
#define MPC11_Q_YN_ADDR 145        /*Q_yN: 6x6 matrix values */
#define MPC11_Q_ADDR 181        /*Q: [1 1] array values */
#define MPC11_Q_ADDR 182        /*Q: [1 1] array values */
#define MPC11_LAMBDA_ADDR 183        /*lambda: [1 1] array values */
#define MPC11_R_Q_PP_ADDR 184        /*R_q_pp: 7x7 matrix values */
#define MPC11_X_MIN_ADDR 233        /*x_min: [14 1] array values */
#define MPC11_X_MAX_ADDR 247        /*x_max: [14 1] array values */
#define MPC11_U_MIN_ADDR 261        /*u_min: [7 1] array values */
#define MPC11_U_MAX_ADDR 268        /*u_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC11_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(4x1), t(1x1)] */
#define MPC11_IN_INIT_GUESS_ADDR 5        /* init_guess = [u(2x5), x(4x6), theta(1x6), lambda_u(2x5), lambda_x(4x6), lambda_theta(1x6), g(4x6)] */
#define MPC11_IN_PARAM_WEIGHT_ADDR 109        /* param_weight = [Q_y(6x6), Q_yN(6x6), Q(1x1), Q(1x1), lambda(1x1), R_q_pp(7x7), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC11_U_OPT_LEN 2        /*u_opt: [2 1] array values */
#define MPC11_U_OUT_LEN 10        /*u_out: 2x5 matrix values */
#define MPC11_X_OUT_LEN 24        /*x_out: 4x6 matrix values */
#define MPC11_THETA_OUT_LEN 6        /*theta_out: [1 6] array values */
#define MPC11_LAMBDA_U_OUT_LEN 10        /*lambda_u_out: 2x5 matrix values */
#define MPC11_LAMBDA_X_OUT_LEN 24        /*lambda_x_out: 4x6 matrix values */
#define MPC11_LAMBDA_THETA_OUT_LEN 6        /*lambda_theta_out: [1 6] array values */
#define MPC11_G_OUT_LEN 24        /*g_out: 4x6 matrix values */
#define MPC11_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC11_J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define MPC11_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC11_J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define MPC11_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */
#define MPC11_J_THETA_LEN 1        /*J_theta: [1 1] array values */
#define MPC11_J_THETAN_LEN 1        /*J_thetaN: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC11_U_OPT_ADDR 275        /*u_opt: [2 1] array values */
#define MPC11_U_OUT_ADDR 277        /*u_out: 2x5 matrix values */
#define MPC11_X_OUT_ADDR 287        /*x_out: 4x6 matrix values */
#define MPC11_THETA_OUT_ADDR 311        /*theta_out: [1 6] array values */
#define MPC11_LAMBDA_U_OUT_ADDR 317        /*lambda_u_out: 2x5 matrix values */
#define MPC11_LAMBDA_X_OUT_ADDR 327        /*lambda_x_out: 4x6 matrix values */
#define MPC11_LAMBDA_THETA_OUT_ADDR 351        /*lambda_theta_out: [1 6] array values */
#define MPC11_G_OUT_ADDR 357        /*g_out: 4x6 matrix values */
#define MPC11_J_YT_ADDR 381        /*J_yt: [1 1] array values */
#define MPC11_J_YT_N_ADDR 382        /*J_yt_N: [1 1] array values */
#define MPC11_J_YR_ADDR 383        /*J_yr: [1 1] array values */
#define MPC11_J_YR_N_ADDR 384        /*J_yr_N: [1 1] array values */
#define MPC11_J_Q_PP_ADDR 385        /*J_q_pp: [1 1] array values */
#define MPC11_J_THETA_ADDR 386        /*J_theta: [1 1] array values */
#define MPC11_J_THETAN_ADDR 387        /*J_thetaN: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC11_OUT_U_OPT_ADDR 275        /* u_opt = [u[0:1](2x1)] */
#define MPC11_OUT_INIT_GUESS_OUT_ADDR 277        /* init_guess_out = [u_out(2x5), x_out(4x6), theta_out(1x6), lambda_u_out(2x5), lambda_x_out(4x6), lambda_theta_out(1x6), g_out(4x6)] */
#define MPC11_OUT_COST_FUN_1_ADDR 381        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC11_OUT_COST_FUN_2_ADDR 382        /* cost_fun_2 = [J_yt_N(1x1)] */
#define MPC11_OUT_COST_FUN_3_ADDR 383        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC11_OUT_COST_FUN_4_ADDR 384        /* cost_fun_4 = [J_yr_N(1x1)] */
#define MPC11_OUT_COST_FUN_5_ADDR 385        /* cost_fun_5 = [J_q_pp(1x1)] */
#define MPC11_OUT_COST_FUN_6_ADDR 386        /* cost_fun_6 = [J_theta(1x1)] */
#define MPC11_OUT_COST_FUN_7_ADDR 387        /* cost_fun_7 = [J_thetaN(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
