/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC6_alloc_mem(void);
int MPC6_init_mem(int mem);
void MPC6_free_mem(int mem);
int MPC6_checkout(void);
void MPC6_release(int mem);
void MPC6_incref(void);
void MPC6_decref(void);
casadi_int MPC6_n_in(void);
casadi_int MPC6_n_out(void);
casadi_real MPC6_default_in(casadi_int i);
const char* MPC6_name_in(casadi_int i);
const char* MPC6_name_out(casadi_int i);
const casadi_int* MPC6_sparsity_in(casadi_int i);
const casadi_int* MPC6_sparsity_out(casadi_int i);
int MPC6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC6_SZ_ARG 24
#define MPC6_SZ_RES 17
#define MPC6_SZ_IW 1985
#define MPC6_SZ_W 47469
#ifdef __cplusplus
} /* extern "C" */
#endif
