/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC6_IW_LEN 1840
#define MPC6_ARG_LEN 24
#define MPC6_RES_LEN 17
#define MPC6_W_LEN 40154
static const uint32_t MPC6_ARG[] = {0,139,723};
static const uint32_t MPC6_RES[] = {924,930,1514,1515,1516,1517,1518};
#define MPC6_W_END_ADDRESS 1519

// INPUT DIMENSIONS:
#define MPC6_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC6_ZT_0_LEN 13        /*zt_0: [13 1] array values */
#define MPC6_Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define MPC6_Y_D_P_LEN 36        /*y_d_p: 6x6 matrix values */
#define MPC6_Y_D_PP_LEN 36        /*y_d_pp: 6x6 matrix values */
#define MPC6_U_LEN 30        /*u: 6x5 matrix values */
#define MPC6_X_LEN 72        /*x: 12x6 matrix values */
#define MPC6_ZT_LEN 78        /*zt: 13x6 matrix values */
#define MPC6_ALPHA_T_LEN 36        /*alpha_t: 6x6 matrix values */
#define MPC6_LAMBDA_U_LEN 30        /*lambda_u: 6x5 matrix values */
#define MPC6_LAMBDA_X_LEN 72        /*lambda_x: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_LEN 78        /*lambda_zt: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_LEN 36        /*lambda_alpha_t: 6x6 matrix values */
#define MPC6_G_LEN 240        /*g: 12x20 matrix values */
#define MPC6_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC6_R_Q_PP_LEN 49        /*R_q_pp: 7x7 matrix values */
#define MPC6_Q_Y_P_REF_LEN 36        /*Q_y_p_ref: 6x6 matrix values */
#define MPC6_Q_Y_REF_LEN 36        /*Q_y_ref: 6x6 matrix values */
#define MPC6_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC6_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC6_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC6_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC6_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC6_U_MAX_LEN 7        /*u_max: [7 1] array values */

#define MPC6_REFERENCE_VALUES_LEN 139        /* reference_values = [x_k(12x1), zt_0(13x1), y_d(7x6), y_d_p(6x6), y_d_pp(6x6)] */
#define MPC6_INIT_GUESS_LEN 584        /* init_guess = [u(6x5), x(12x6), zt(13x6), alpha_t(6x6), lambda_u(6x5), lambda_x(12x6), lambda_zt(13x6), lambda_alpha_t(6x6), g(12x20)] */
#define MPC6_PARAM_WEIGHT_LEN 201        /* param_weight = [Q_y(6x6), R_q_pp(7x7), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// INPUT ADDRESSES:
#define MPC6_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC6_ZT_0_ADDR 12        /*zt_0: [13 1] array values */
#define MPC6_Y_D_ADDR 25        /*y_d: 7x6 matrix values */
#define MPC6_Y_D_P_ADDR 67        /*y_d_p: 6x6 matrix values */
#define MPC6_Y_D_PP_ADDR 103        /*y_d_pp: 6x6 matrix values */
#define MPC6_U_ADDR 139        /*u: 6x5 matrix values */
#define MPC6_X_ADDR 169        /*x: 12x6 matrix values */
#define MPC6_ZT_ADDR 241        /*zt: 13x6 matrix values */
#define MPC6_ALPHA_T_ADDR 319        /*alpha_t: 6x6 matrix values */
#define MPC6_LAMBDA_U_ADDR 355        /*lambda_u: 6x5 matrix values */
#define MPC6_LAMBDA_X_ADDR 385        /*lambda_x: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_ADDR 457        /*lambda_zt: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_ADDR 535        /*lambda_alpha_t: 6x6 matrix values */
#define MPC6_G_ADDR 571        /*g: 12x20 matrix values */
#define MPC6_Q_Y_ADDR 811        /*Q_y: 6x6 matrix values */
#define MPC6_R_Q_PP_ADDR 847        /*R_q_pp: 7x7 matrix values */
#define MPC6_Q_Y_P_REF_ADDR 896        /*Q_y_p_ref: 6x6 matrix values */
#define MPC6_Q_Y_REF_ADDR 932        /*Q_y_ref: 6x6 matrix values */
#define MPC6_EPSILON_ADDR 968        /*epsilon: [1 1] array values */
#define MPC6_EPSILON_ADDR 969        /*epsilon: [1 1] array values */
#define MPC6_X_MIN_ADDR 970        /*x_min: [14 1] array values */
#define MPC6_X_MAX_ADDR 984        /*x_max: [14 1] array values */
#define MPC6_U_MIN_ADDR 998        /*u_min: [7 1] array values */
#define MPC6_U_MAX_ADDR 1005        /*u_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC6_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), zt_0(13x1), y_d(7x6), y_d_p(6x6), y_d_pp(6x6)] */
#define MPC6_IN_INIT_GUESS_ADDR 139        /* init_guess = [u(6x5), x(12x6), zt(13x6), alpha_t(6x6), lambda_u(6x5), lambda_x(12x6), lambda_zt(13x6), lambda_alpha_t(6x6), g(12x20)] */
#define MPC6_IN_PARAM_WEIGHT_ADDR 723        /* param_weight = [Q_y(6x6), R_q_pp(7x7), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC6_U_OPT_LEN 6        /*u_opt: [6 1] array values */
#define MPC6_U_OUT_LEN 30        /*u_out: 6x5 matrix values */
#define MPC6_X_OUT_LEN 72        /*x_out: 12x6 matrix values */
#define MPC6_ZT_OUT_LEN 78        /*zt_out: 13x6 matrix values */
#define MPC6_ALPHA_T_OUT_LEN 36        /*alpha_t_out: 6x6 matrix values */
#define MPC6_LAMBDA_U_OUT_LEN 30        /*lambda_u_out: 6x5 matrix values */
#define MPC6_LAMBDA_X_OUT_LEN 72        /*lambda_x_out: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_OUT_LEN 78        /*lambda_zt_out: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_OUT_LEN 36        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC6_G_OUT_LEN 240        /*g_out: 12x20 matrix values */
#define MPC6_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC6_JT_YY_REF_LEN 1        /*Jt_yy_ref: [1 1] array values */
#define MPC6_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC6_JR_YY_REF_LEN 1        /*Jr_yy_ref: [1 1] array values */
#define MPC6_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC6_U_OPT_ADDR 924        /*u_opt: [6 1] array values */
#define MPC6_U_OUT_ADDR 930        /*u_out: 6x5 matrix values */
#define MPC6_X_OUT_ADDR 960        /*x_out: 12x6 matrix values */
#define MPC6_ZT_OUT_ADDR 1032        /*zt_out: 13x6 matrix values */
#define MPC6_ALPHA_T_OUT_ADDR 1110        /*alpha_t_out: 6x6 matrix values */
#define MPC6_LAMBDA_U_OUT_ADDR 1146        /*lambda_u_out: 6x5 matrix values */
#define MPC6_LAMBDA_X_OUT_ADDR 1176        /*lambda_x_out: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_OUT_ADDR 1248        /*lambda_zt_out: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_OUT_ADDR 1326        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC6_G_OUT_ADDR 1362        /*g_out: 12x20 matrix values */
#define MPC6_J_YT_ADDR 1602        /*J_yt: [1 1] array values */
#define MPC6_JT_YY_REF_ADDR 1603        /*Jt_yy_ref: [1 1] array values */
#define MPC6_J_YR_ADDR 1604        /*J_yr: [1 1] array values */
#define MPC6_JR_YY_REF_ADDR 1605        /*Jr_yy_ref: [1 1] array values */
#define MPC6_J_Q_PP_ADDR 1606        /*J_q_pp: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC6_OUT_U_OPT_ADDR 924        /* u_opt = [u[0:5](6x1)] */
#define MPC6_OUT_INIT_GUESS_OUT_ADDR 930        /* init_guess_out = [u_out(6x5), x_out(12x6), zt_out(13x6), alpha_t_out(6x6), lambda_u_out(6x5), lambda_x_out(12x6), lambda_zt_out(13x6), lambda_alpha_t_out(6x6), g_out(12x20)] */
#define MPC6_OUT_COST_FUN_1_ADDR 1514        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC6_OUT_COST_FUN_2_ADDR 1515        /* cost_fun_2 = [Jt_yy_ref(1x1)] */
#define MPC6_OUT_COST_FUN_3_ADDR 1516        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC6_OUT_COST_FUN_4_ADDR 1517        /* cost_fun_4 = [Jr_yy_ref(1x1)] */
#define MPC6_OUT_COST_FUN_5_ADDR 1518        /* cost_fun_5 = [J_q_pp(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
