/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC6_IW_LEN 1900
#define MPC6_ARG_LEN 36
#define MPC6_RES_LEN 22
#define MPC6_W_LEN 43641
static const uint32_t MPC6_ARG[] = {0,355,957};
static const uint32_t MPC6_RES[] = {1818,1830,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441};
#define MPC6_W_END_ADDRESS 2442

// INPUT DIMENSIONS:
#define MPC6_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC6_ZT_K_LEN 13        /*zt_k: [13 1] array values */
#define MPC6_Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define MPC6_Y_D_P_LEN 36        /*y_d_p: 6x6 matrix values */
#define MPC6_Y_D_PP_LEN 36        /*y_d_pp: 6x6 matrix values */
#define MPC6_U_PREV_LEN 30        /*u_prev: 6x5 matrix values */
#define MPC6_X_PREV_LEN 72        /*x_prev: 12x6 matrix values */
#define MPC6_Z_PREV_LEN 78        /*z_prev: 13x6 matrix values */
#define MPC6_ALPHA_PREV_LEN 36        /*alpha_prev: 6x6 matrix values */
#define MPC6_U_LEN 30        /*u: 6x5 matrix values */
#define MPC6_X_LEN 72        /*x: 12x6 matrix values */
#define MPC6_ZT_LEN 78        /*zt: 13x6 matrix values */
#define MPC6_ALPHA_T_LEN 36        /*alpha_t: 6x6 matrix values */
#define MPC6_Q_PP_0_LEN 6        /*q_pp_0: [6 1] array values */
#define MPC6_LAMBDA_U_LEN 30        /*lambda_u: 6x5 matrix values */
#define MPC6_LAMBDA_X_LEN 72        /*lambda_x: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_LEN 78        /*lambda_zt: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_LEN 36        /*lambda_alpha_t: 6x6 matrix values */
#define MPC6_LAMBDA_Q_PP_0_LEN 6        /*lambda_q_pp_0: [6 1] array values */
#define MPC6_G_LEN 252        /*g: 12x21 matrix values */
#define MPC6_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC6_Q_Y_P_REF_LEN 36        /*Q_y_p_ref: 6x6 matrix values */
#define MPC6_Q_Y_REF_LEN 36        /*Q_y_ref: 6x6 matrix values */
#define MPC6_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC6_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC6_R_U0_LEN 49        /*R_u0: 7x7 matrix values */
#define MPC6_R_U_LEN 49        /*R_u: 7x7 matrix values */
#define MPC6_R_X0_LEN 196        /*R_x0: 14x14 matrix values */
#define MPC6_R_X_LEN 196        /*R_x: 14x14 matrix values */
#define MPC6_R_Z_LEN 169        /*R_z: 13x13 matrix values */
#define MPC6_R_ALPHA_LEN 36        /*R_alpha: 6x6 matrix values */
#define MPC6_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC6_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC6_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC6_U_MAX_LEN 7        /*u_max: [7 1] array values */
#define MPC6_Q_PP_MIN_LEN 7        /*q_pp_min: [7 1] array values */
#define MPC6_Q_PP_MAX_LEN 7        /*q_pp_max: [7 1] array values */

#define MPC6_REFERENCE_VALUES_LEN 355        /* reference_values = [x_k(12x1), zt_k(13x1), y_d(7x6), y_d_p(6x6), y_d_pp(6x6), u_prev(6x5), x_prev(12x6), z_prev(13x6), alpha_prev(6x6)] */
#define MPC6_INIT_GUESS_LEN 602        /* init_guess = [u(6x5), x(12x6), zt(13x6), alpha_t(6x6), q_pp_0(6x1), lambda_u(6x5), lambda_x(12x6), lambda_zt(13x6), lambda_alpha_t(6x6), lambda_q_pp_0(6x1), g(12x21)] */
#define MPC6_PARAM_WEIGHT_LEN 861        /* param_weight = [Q_y(6x6), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), R_u0(7x7), R_u(7x7), R_x0(14x14), R_x(14x14), R_z(13x13), R_alpha(6x6), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1), q_pp_min(7x1), q_pp_max(7x1)] */

// INPUT ADDRESSES:
#define MPC6_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC6_ZT_K_ADDR 12        /*zt_k: [13 1] array values */
#define MPC6_Y_D_ADDR 25        /*y_d: 7x6 matrix values */
#define MPC6_Y_D_P_ADDR 67        /*y_d_p: 6x6 matrix values */
#define MPC6_Y_D_PP_ADDR 103        /*y_d_pp: 6x6 matrix values */
#define MPC6_U_PREV_ADDR 139        /*u_prev: 6x5 matrix values */
#define MPC6_X_PREV_ADDR 169        /*x_prev: 12x6 matrix values */
#define MPC6_Z_PREV_ADDR 241        /*z_prev: 13x6 matrix values */
#define MPC6_ALPHA_PREV_ADDR 319        /*alpha_prev: 6x6 matrix values */
#define MPC6_U_ADDR 355        /*u: 6x5 matrix values */
#define MPC6_X_ADDR 385        /*x: 12x6 matrix values */
#define MPC6_ZT_ADDR 457        /*zt: 13x6 matrix values */
#define MPC6_ALPHA_T_ADDR 535        /*alpha_t: 6x6 matrix values */
#define MPC6_Q_PP_0_ADDR 571        /*q_pp_0: [6 1] array values */
#define MPC6_LAMBDA_U_ADDR 577        /*lambda_u: 6x5 matrix values */
#define MPC6_LAMBDA_X_ADDR 607        /*lambda_x: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_ADDR 679        /*lambda_zt: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_ADDR 757        /*lambda_alpha_t: 6x6 matrix values */
#define MPC6_LAMBDA_Q_PP_0_ADDR 793        /*lambda_q_pp_0: [6 1] array values */
#define MPC6_G_ADDR 799        /*g: 12x21 matrix values */
#define MPC6_Q_Y_ADDR 1051        /*Q_y: 6x6 matrix values */
#define MPC6_Q_Y_P_REF_ADDR 1087        /*Q_y_p_ref: 6x6 matrix values */
#define MPC6_Q_Y_REF_ADDR 1123        /*Q_y_ref: 6x6 matrix values */
#define MPC6_EPSILON_ADDR 1159        /*epsilon: [1 1] array values */
#define MPC6_EPSILON_ADDR 1160        /*epsilon: [1 1] array values */
#define MPC6_R_U0_ADDR 1161        /*R_u0: 7x7 matrix values */
#define MPC6_R_U_ADDR 1210        /*R_u: 7x7 matrix values */
#define MPC6_R_X0_ADDR 1259        /*R_x0: 14x14 matrix values */
#define MPC6_R_X_ADDR 1455        /*R_x: 14x14 matrix values */
#define MPC6_R_Z_ADDR 1651        /*R_z: 13x13 matrix values */
#define MPC6_R_ALPHA_ADDR 1820        /*R_alpha: 6x6 matrix values */
#define MPC6_X_MIN_ADDR 1856        /*x_min: [14 1] array values */
#define MPC6_X_MAX_ADDR 1870        /*x_max: [14 1] array values */
#define MPC6_U_MIN_ADDR 1884        /*u_min: [7 1] array values */
#define MPC6_U_MAX_ADDR 1891        /*u_max: [7 1] array values */
#define MPC6_Q_PP_MIN_ADDR 1898        /*q_pp_min: [7 1] array values */
#define MPC6_Q_PP_MAX_ADDR 1905        /*q_pp_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC6_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), zt_k(13x1), y_d(7x6), y_d_p(6x6), y_d_pp(6x6), u_prev(6x5), x_prev(12x6), z_prev(13x6), alpha_prev(6x6)] */
#define MPC6_IN_INIT_GUESS_ADDR 355        /* init_guess = [u(6x5), x(12x6), zt(13x6), alpha_t(6x6), q_pp_0(6x1), lambda_u(6x5), lambda_x(12x6), lambda_zt(13x6), lambda_alpha_t(6x6), lambda_q_pp_0(6x1), g(12x21)] */
#define MPC6_IN_PARAM_WEIGHT_ADDR 957        /* param_weight = [Q_y(6x6), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), R_u0(7x7), R_u(7x7), R_x0(14x14), R_x(14x14), R_z(13x13), R_alpha(6x6), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1), q_pp_min(7x1), q_pp_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC6_U_OPT_LEN 12        /*u_opt: [12 1] array values */
#define MPC6_U_OUT_LEN 30        /*u_out: 6x5 matrix values */
#define MPC6_X_OUT_LEN 72        /*x_out: 12x6 matrix values */
#define MPC6_ZT_OUT_LEN 78        /*zt_out: 13x6 matrix values */
#define MPC6_ALPHA_T_OUT_LEN 36        /*alpha_t_out: 6x6 matrix values */
#define MPC6_Q_PP_0_OUT_LEN 6        /*q_pp_0_out: [6 1] array values */
#define MPC6_LAMBDA_U_OUT_LEN 30        /*lambda_u_out: 6x5 matrix values */
#define MPC6_LAMBDA_X_OUT_LEN 72        /*lambda_x_out: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_OUT_LEN 78        /*lambda_zt_out: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_OUT_LEN 36        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC6_LAMBDA_Q_PP_0_OUT_LEN 6        /*lambda_q_pp_0_out: [6 1] array values */
#define MPC6_G_OUT_LEN 252        /*g_out: 12x21 matrix values */
#define MPC6_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC6_JT_YY_REF_LEN 1        /*Jt_yy_ref: [1 1] array values */
#define MPC6_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC6_JR_YY_REF_LEN 1        /*Jr_yy_ref: [1 1] array values */
#define MPC6_J_U_LEN 1        /*J_u: [1 1] array values */
#define MPC6_J_X _LEN 1        /*J_x : [1 1] array values */
#define MPC6_J_Z_LEN 1        /*J_z: [1 1] array values */
#define MPC6_J_ALPHA_LEN 1        /*J_alpha: [1 1] array values */
#define MPC6_J_U0_LEN 1        /*J_u0: [1 1] array values */
#define MPC6_J_X0_LEN 1        /*J_x0: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC6_U_OPT_ADDR 1818        /*u_opt: [12 1] array values */
#define MPC6_U_OUT_ADDR 1830        /*u_out: 6x5 matrix values */
#define MPC6_X_OUT_ADDR 1860        /*x_out: 12x6 matrix values */
#define MPC6_ZT_OUT_ADDR 1932        /*zt_out: 13x6 matrix values */
#define MPC6_ALPHA_T_OUT_ADDR 2010        /*alpha_t_out: 6x6 matrix values */
#define MPC6_Q_PP_0_OUT_ADDR 2046        /*q_pp_0_out: [6 1] array values */
#define MPC6_LAMBDA_U_OUT_ADDR 2052        /*lambda_u_out: 6x5 matrix values */
#define MPC6_LAMBDA_X_OUT_ADDR 2082        /*lambda_x_out: 12x6 matrix values */
#define MPC6_LAMBDA_ZT_OUT_ADDR 2154        /*lambda_zt_out: 13x6 matrix values */
#define MPC6_LAMBDA_ALPHA_T_OUT_ADDR 2232        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC6_LAMBDA_Q_PP_0_OUT_ADDR 2268        /*lambda_q_pp_0_out: [6 1] array values */
#define MPC6_G_OUT_ADDR 2274        /*g_out: 12x21 matrix values */
#define MPC6_J_YT_ADDR 2526        /*J_yt: [1 1] array values */
#define MPC6_JT_YY_REF_ADDR 2527        /*Jt_yy_ref: [1 1] array values */
#define MPC6_J_YR_ADDR 2528        /*J_yr: [1 1] array values */
#define MPC6_JR_YY_REF_ADDR 2529        /*Jr_yy_ref: [1 1] array values */
#define MPC6_J_U_ADDR 2530        /*J_u: [1 1] array values */
#define MPC6_J_X _ADDR 2531        /*J_x : [1 1] array values */
#define MPC6_J_Z_ADDR 2532        /*J_z: [1 1] array values */
#define MPC6_J_ALPHA_ADDR 2533        /*J_alpha: [1 1] array values */
#define MPC6_J_U0_ADDR 2534        /*J_u0: [1 1] array values */
#define MPC6_J_X0_ADDR 2535        /*J_x0: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC6_OUT_U_OPT_ADDR 1818        /* u_opt = [u[0:221](12x1)] */
#define MPC6_OUT_INIT_GUESS_OUT_ADDR 1830        /* init_guess_out = [u_out(6x5), x_out(12x6), zt_out(13x6), alpha_t_out(6x6), q_pp_0_out(6x1), lambda_u_out(6x5), lambda_x_out(12x6), lambda_zt_out(13x6), lambda_alpha_t_out(6x6), lambda_q_pp_0_out(6x1), g_out(12x21)] */
#define MPC6_OUT_COST_FUN_1_ADDR 2432        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC6_OUT_COST_FUN_2_ADDR 2433        /* cost_fun_2 = [Jt_yy_ref(1x1)] */
#define MPC6_OUT_COST_FUN_3_ADDR 2434        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC6_OUT_COST_FUN_4_ADDR 2435        /* cost_fun_4 = [Jr_yy_ref(1x1)] */
#define MPC6_OUT_COST_FUN_5_ADDR 2436        /* cost_fun_5 = [J_u(1x1)] */
#define MPC6_OUT_COST_FUN_6_ADDR 2437        /* cost_fun_6 = [J_x (1x1)] */
#define MPC6_OUT_COST_FUN_7_ADDR 2438        /* cost_fun_7 = [J_z(1x1)] */
#define MPC6_OUT_COST_FUN_8_ADDR 2439        /* cost_fun_8 = [J_alpha(1x1)] */
#define MPC6_OUT_COST_FUN_9_ADDR 2440        /* cost_fun_9 = [J_u0(1x1)] */
#define MPC6_OUT_COST_FUN_10_ADDR 2441        /* cost_fun_10 = [J_x0(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
