/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC7_alloc_mem(void);
int MPC7_init_mem(int mem);
void MPC7_free_mem(int mem);
int MPC7_checkout(void);
void MPC7_release(int mem);
void MPC7_incref(void);
void MPC7_decref(void);
casadi_int MPC7_n_in(void);
casadi_int MPC7_n_out(void);
casadi_real MPC7_default_in(casadi_int i);
const char* MPC7_name_in(casadi_int i);
const char* MPC7_name_out(casadi_int i);
const casadi_int* MPC7_sparsity_in(casadi_int i);
const casadi_int* MPC7_sparsity_out(casadi_int i);
int MPC7_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC7_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC7_SZ_ARG 24
#define MPC7_SZ_RES 17
#define MPC7_SZ_IW 595
#define MPC7_SZ_W 8200
#ifdef __cplusplus
} /* extern "C" */
#endif
