/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC7_IW_LEN 1840
#define MPC7_ARG_LEN 36
#define MPC7_RES_LEN 22
#define MPC7_W_LEN 39384
static const uint32_t MPC7_ARG[] = {0,342,926};
static const uint32_t MPC7_RES[] = {1787,1799,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392};
#define MPC7_W_END_ADDRESS 2393

// INPUT DIMENSIONS:
#define MPC7_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC7_ZT_K_LEN 12        /*zt_k: [12 1] array values */
#define MPC7_Y_D_LEN 36        /*y_d: 6x6 matrix values */
#define MPC7_Y_D_P_LEN 36        /*y_d_p: 6x6 matrix values */
#define MPC7_Y_D_PP_LEN 36        /*y_d_pp: 6x6 matrix values */
#define MPC7_U_PREV_LEN 30        /*u_prev: 6x5 matrix values */
#define MPC7_X_PREV_LEN 72        /*x_prev: 12x6 matrix values */
#define MPC7_Z_PREV_LEN 72        /*z_prev: 12x6 matrix values */
#define MPC7_ALPHA_PREV_LEN 36        /*alpha_prev: 6x6 matrix values */
#define MPC7_U_LEN 30        /*u: 6x5 matrix values */
#define MPC7_X_LEN 72        /*x: 12x6 matrix values */
#define MPC7_ZT_LEN 72        /*zt: 12x6 matrix values */
#define MPC7_ALPHA_T_LEN 36        /*alpha_t: 6x6 matrix values */
#define MPC7_Q_PP_0_LEN 6        /*q_pp_0: [6 1] array values */
#define MPC7_LAMBDA_U_LEN 30        /*lambda_u: 6x5 matrix values */
#define MPC7_LAMBDA_X_LEN 72        /*lambda_x: 12x6 matrix values */
#define MPC7_LAMBDA_ZT_LEN 72        /*lambda_zt: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_LEN 36        /*lambda_alpha_t: 6x6 matrix values */
#define MPC7_LAMBDA_Q_PP_0_LEN 6        /*lambda_q_pp_0: [6 1] array values */
#define MPC7_G_LEN 252        /*g: 12x21 matrix values */
#define MPC7_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC7_Q_Y_P_REF_LEN 36        /*Q_y_p_ref: 6x6 matrix values */
#define MPC7_Q_Y_REF_LEN 36        /*Q_y_ref: 6x6 matrix values */
#define MPC7_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC7_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC7_R_U0_LEN 49        /*R_u0: 7x7 matrix values */
#define MPC7_R_U_LEN 49        /*R_u: 7x7 matrix values */
#define MPC7_R_X0_LEN 196        /*R_x0: 14x14 matrix values */
#define MPC7_R_X_LEN 196        /*R_x: 14x14 matrix values */
#define MPC7_R_Z_LEN 169        /*R_z: 13x13 matrix values */
#define MPC7_R_ALPHA_LEN 36        /*R_alpha: 6x6 matrix values */
#define MPC7_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC7_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC7_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC7_U_MAX_LEN 7        /*u_max: [7 1] array values */
#define MPC7_Q_PP_MIN_LEN 7        /*q_pp_min: [7 1] array values */
#define MPC7_Q_PP_MAX_LEN 7        /*q_pp_max: [7 1] array values */

#define MPC7_REFERENCE_VALUES_LEN 342        /* reference_values = [x_k(12x1), zt_k(12x1), y_d(6x6), y_d_p(6x6), y_d_pp(6x6), u_prev(6x5), x_prev(12x6), z_prev(12x6), alpha_prev(6x6)] */
#define MPC7_INIT_GUESS_LEN 584        /* init_guess = [u(6x5), x(12x6), zt(12x6), alpha_t(6x6), q_pp_0(6x1), lambda_u(6x5), lambda_x(12x6), lambda_zt(12x6), lambda_alpha_t(6x6), lambda_q_pp_0(6x1), g(12x21)] */
#define MPC7_PARAM_WEIGHT_LEN 861        /* param_weight = [Q_y(6x6), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), R_u0(7x7), R_u(7x7), R_x0(14x14), R_x(14x14), R_z(13x13), R_alpha(6x6), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1), q_pp_min(7x1), q_pp_max(7x1)] */

// INPUT ADDRESSES:
#define MPC7_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC7_ZT_K_ADDR 12        /*zt_k: [12 1] array values */
#define MPC7_Y_D_ADDR 24        /*y_d: 6x6 matrix values */
#define MPC7_Y_D_P_ADDR 60        /*y_d_p: 6x6 matrix values */
#define MPC7_Y_D_PP_ADDR 96        /*y_d_pp: 6x6 matrix values */
#define MPC7_U_PREV_ADDR 132        /*u_prev: 6x5 matrix values */
#define MPC7_X_PREV_ADDR 162        /*x_prev: 12x6 matrix values */
#define MPC7_Z_PREV_ADDR 234        /*z_prev: 12x6 matrix values */
#define MPC7_ALPHA_PREV_ADDR 306        /*alpha_prev: 6x6 matrix values */
#define MPC7_U_ADDR 342        /*u: 6x5 matrix values */
#define MPC7_X_ADDR 372        /*x: 12x6 matrix values */
#define MPC7_ZT_ADDR 444        /*zt: 12x6 matrix values */
#define MPC7_ALPHA_T_ADDR 516        /*alpha_t: 6x6 matrix values */
#define MPC7_Q_PP_0_ADDR 552        /*q_pp_0: [6 1] array values */
#define MPC7_LAMBDA_U_ADDR 558        /*lambda_u: 6x5 matrix values */
#define MPC7_LAMBDA_X_ADDR 588        /*lambda_x: 12x6 matrix values */
#define MPC7_LAMBDA_ZT_ADDR 660        /*lambda_zt: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_ADDR 732        /*lambda_alpha_t: 6x6 matrix values */
#define MPC7_LAMBDA_Q_PP_0_ADDR 768        /*lambda_q_pp_0: [6 1] array values */
#define MPC7_G_ADDR 774        /*g: 12x21 matrix values */
#define MPC7_Q_Y_ADDR 1026        /*Q_y: 6x6 matrix values */
#define MPC7_Q_Y_P_REF_ADDR 1062        /*Q_y_p_ref: 6x6 matrix values */
#define MPC7_Q_Y_REF_ADDR 1098        /*Q_y_ref: 6x6 matrix values */
#define MPC7_EPSILON_ADDR 1134        /*epsilon: [1 1] array values */
#define MPC7_EPSILON_ADDR 1135        /*epsilon: [1 1] array values */
#define MPC7_R_U0_ADDR 1136        /*R_u0: 7x7 matrix values */
#define MPC7_R_U_ADDR 1185        /*R_u: 7x7 matrix values */
#define MPC7_R_X0_ADDR 1234        /*R_x0: 14x14 matrix values */
#define MPC7_R_X_ADDR 1430        /*R_x: 14x14 matrix values */
#define MPC7_R_Z_ADDR 1626        /*R_z: 13x13 matrix values */
#define MPC7_R_ALPHA_ADDR 1795        /*R_alpha: 6x6 matrix values */
#define MPC7_X_MIN_ADDR 1831        /*x_min: [14 1] array values */
#define MPC7_X_MAX_ADDR 1845        /*x_max: [14 1] array values */
#define MPC7_U_MIN_ADDR 1859        /*u_min: [7 1] array values */
#define MPC7_U_MAX_ADDR 1866        /*u_max: [7 1] array values */
#define MPC7_Q_PP_MIN_ADDR 1873        /*q_pp_min: [7 1] array values */
#define MPC7_Q_PP_MAX_ADDR 1880        /*q_pp_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC7_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), zt_k(12x1), y_d(6x6), y_d_p(6x6), y_d_pp(6x6), u_prev(6x5), x_prev(12x6), z_prev(12x6), alpha_prev(6x6)] */
#define MPC7_IN_INIT_GUESS_ADDR 342        /* init_guess = [u(6x5), x(12x6), zt(12x6), alpha_t(6x6), q_pp_0(6x1), lambda_u(6x5), lambda_x(12x6), lambda_zt(12x6), lambda_alpha_t(6x6), lambda_q_pp_0(6x1), g(12x21)] */
#define MPC7_IN_PARAM_WEIGHT_ADDR 926        /* param_weight = [Q_y(6x6), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), R_u0(7x7), R_u(7x7), R_x0(14x14), R_x(14x14), R_z(13x13), R_alpha(6x6), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1), q_pp_min(7x1), q_pp_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC7_U_OPT_LEN 12        /*u_opt: [12 1] array values */
#define MPC7_U_OUT_LEN 30        /*u_out: 6x5 matrix values */
#define MPC7_X_OUT_LEN 72        /*x_out: 12x6 matrix values */
#define MPC7_ZT_OUT_LEN 72        /*zt_out: 12x6 matrix values */
#define MPC7_ALPHA_T_OUT_LEN 36        /*alpha_t_out: 6x6 matrix values */
#define MPC7_Q_PP_0_OUT_LEN 6        /*q_pp_0_out: [6 1] array values */
#define MPC7_LAMBDA_U_OUT_LEN 30        /*lambda_u_out: 6x5 matrix values */
#define MPC7_LAMBDA_X_OUT_LEN 72        /*lambda_x_out: 12x6 matrix values */
#define MPC7_LAMBDA_ZT_OUT_LEN 72        /*lambda_zt_out: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_OUT_LEN 36        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC7_LAMBDA_Q_PP_0_OUT_LEN 6        /*lambda_q_pp_0_out: [6 1] array values */
#define MPC7_G_OUT_LEN 252        /*g_out: 12x21 matrix values */
#define MPC7_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC7_JT_YY_REF_LEN 1        /*Jt_yy_ref: [1 1] array values */
#define MPC7_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC7_JR_YY_REF_LEN 1        /*Jr_yy_ref: [1 1] array values */
#define MPC7_J_U_LEN 1        /*J_u: [1 1] array values */
#define MPC7_J_X _LEN 1        /*J_x : [1 1] array values */
#define MPC7_J_Z_LEN 1        /*J_z: [1 1] array values */
#define MPC7_J_ALPHA_LEN 1        /*J_alpha: [1 1] array values */
#define MPC7_J_U0_LEN 1        /*J_u0: [1 1] array values */
#define MPC7_J_X0_LEN 1        /*J_x0: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC7_U_OPT_ADDR 1787        /*u_opt: [12 1] array values */
#define MPC7_U_OUT_ADDR 1799        /*u_out: 6x5 matrix values */
#define MPC7_X_OUT_ADDR 1829        /*x_out: 12x6 matrix values */
#define MPC7_ZT_OUT_ADDR 1901        /*zt_out: 12x6 matrix values */
#define MPC7_ALPHA_T_OUT_ADDR 1973        /*alpha_t_out: 6x6 matrix values */
#define MPC7_Q_PP_0_OUT_ADDR 2009        /*q_pp_0_out: [6 1] array values */
#define MPC7_LAMBDA_U_OUT_ADDR 2015        /*lambda_u_out: 6x5 matrix values */
#define MPC7_LAMBDA_X_OUT_ADDR 2045        /*lambda_x_out: 12x6 matrix values */
#define MPC7_LAMBDA_ZT_OUT_ADDR 2117        /*lambda_zt_out: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_OUT_ADDR 2189        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC7_LAMBDA_Q_PP_0_OUT_ADDR 2225        /*lambda_q_pp_0_out: [6 1] array values */
#define MPC7_G_OUT_ADDR 2231        /*g_out: 12x21 matrix values */
#define MPC7_J_YT_ADDR 2483        /*J_yt: [1 1] array values */
#define MPC7_JT_YY_REF_ADDR 2484        /*Jt_yy_ref: [1 1] array values */
#define MPC7_J_YR_ADDR 2485        /*J_yr: [1 1] array values */
#define MPC7_JR_YY_REF_ADDR 2486        /*Jr_yy_ref: [1 1] array values */
#define MPC7_J_U_ADDR 2487        /*J_u: [1 1] array values */
#define MPC7_J_X _ADDR 2488        /*J_x : [1 1] array values */
#define MPC7_J_Z_ADDR 2489        /*J_z: [1 1] array values */
#define MPC7_J_ALPHA_ADDR 2490        /*J_alpha: [1 1] array values */
#define MPC7_J_U0_ADDR 2491        /*J_u0: [1 1] array values */
#define MPC7_J_X0_ADDR 2492        /*J_x0: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC7_OUT_U_OPT_ADDR 1787        /* u_opt = [u[0:215](12x1)] */
#define MPC7_OUT_INIT_GUESS_OUT_ADDR 1799        /* init_guess_out = [u_out(6x5), x_out(12x6), zt_out(12x6), alpha_t_out(6x6), q_pp_0_out(6x1), lambda_u_out(6x5), lambda_x_out(12x6), lambda_zt_out(12x6), lambda_alpha_t_out(6x6), lambda_q_pp_0_out(6x1), g_out(12x21)] */
#define MPC7_OUT_COST_FUN_1_ADDR 2383        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC7_OUT_COST_FUN_2_ADDR 2384        /* cost_fun_2 = [Jt_yy_ref(1x1)] */
#define MPC7_OUT_COST_FUN_3_ADDR 2385        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC7_OUT_COST_FUN_4_ADDR 2386        /* cost_fun_4 = [Jr_yy_ref(1x1)] */
#define MPC7_OUT_COST_FUN_5_ADDR 2387        /* cost_fun_5 = [J_u(1x1)] */
#define MPC7_OUT_COST_FUN_6_ADDR 2388        /* cost_fun_6 = [J_x (1x1)] */
#define MPC7_OUT_COST_FUN_7_ADDR 2389        /* cost_fun_7 = [J_z(1x1)] */
#define MPC7_OUT_COST_FUN_8_ADDR 2390        /* cost_fun_8 = [J_alpha(1x1)] */
#define MPC7_OUT_COST_FUN_9_ADDR 2391        /* cost_fun_9 = [J_u0(1x1)] */
#define MPC7_OUT_COST_FUN_10_ADDR 2392        /* cost_fun_10 = [J_x0(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
