/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC7_IW_LEN 1925
#define MPC7_ARG_LEN 24
#define MPC7_RES_LEN 17
#define MPC7_W_LEN 46478
static const uint32_t MPC7_ARG[] = {0,134,746};
static const uint32_t MPC7_RES[] = {947,954,1566,1567,1568,1569,1570};
#define MPC7_W_END_ADDRESS 1571

// INPUT DIMENSIONS:
#define MPC7_X_K_LEN 14        /*x_k: [14 1] array values */
#define MPC7_ZT_0_LEN 12        /*zt_0: [12 1] array values */
#define MPC7_Y_D_LEN 36        /*y_d: 6x6 matrix values */
#define MPC7_Y_D_P_LEN 36        /*y_d_p: 6x6 matrix values */
#define MPC7_Y_D_PP_LEN 36        /*y_d_pp: 6x6 matrix values */
#define MPC7_U_LEN 35        /*u: 7x5 matrix values */
#define MPC7_X_LEN 84        /*x: 14x6 matrix values */
#define MPC7_ZT_LEN 72        /*zt: 12x6 matrix values */
#define MPC7_ALPHA_T_LEN 36        /*alpha_t: 6x6 matrix values */
#define MPC7_LAMBDA_U_LEN 35        /*lambda_u: 7x5 matrix values */
#define MPC7_LAMBDA_X_LEN 84        /*lambda_x: 14x6 matrix values */
#define MPC7_LAMBDA_ZT_LEN 72        /*lambda_zt: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_LEN 36        /*lambda_alpha_t: 6x6 matrix values */
#define MPC7_G_LEN 280        /*g: 14x20 matrix values */
#define MPC7_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC7_R_Q_PP_LEN 49        /*R_q_pp: 7x7 matrix values */
#define MPC7_Q_Y_P_REF_LEN 36        /*Q_y_p_ref: 6x6 matrix values */
#define MPC7_Q_Y_REF_LEN 36        /*Q_y_ref: 6x6 matrix values */
#define MPC7_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC7_EPSILON_LEN 1        /*epsilon: [1 1] array values */
#define MPC7_X_MIN_LEN 14        /*x_min: [14 1] array values */
#define MPC7_X_MAX_LEN 14        /*x_max: [14 1] array values */
#define MPC7_U_MIN_LEN 7        /*u_min: [7 1] array values */
#define MPC7_U_MAX_LEN 7        /*u_max: [7 1] array values */

#define MPC7_REFERENCE_VALUES_LEN 134        /* reference_values = [x_k(14x1), zt_0(12x1), y_d(6x6), y_d_p(6x6), y_d_pp(6x6)] */
#define MPC7_INIT_GUESS_LEN 612        /* init_guess = [u(7x5), x(14x6), zt(12x6), alpha_t(6x6), lambda_u(7x5), lambda_x(14x6), lambda_zt(12x6), lambda_alpha_t(6x6), g(14x20)] */
#define MPC7_PARAM_WEIGHT_LEN 201        /* param_weight = [Q_y(6x6), R_q_pp(7x7), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// INPUT ADDRESSES:
#define MPC7_X_K_ADDR 0        /*x_k: [14 1] array values */
#define MPC7_ZT_0_ADDR 14        /*zt_0: [12 1] array values */
#define MPC7_Y_D_ADDR 26        /*y_d: 6x6 matrix values */
#define MPC7_Y_D_P_ADDR 62        /*y_d_p: 6x6 matrix values */
#define MPC7_Y_D_PP_ADDR 98        /*y_d_pp: 6x6 matrix values */
#define MPC7_U_ADDR 134        /*u: 7x5 matrix values */
#define MPC7_X_ADDR 169        /*x: 14x6 matrix values */
#define MPC7_ZT_ADDR 253        /*zt: 12x6 matrix values */
#define MPC7_ALPHA_T_ADDR 325        /*alpha_t: 6x6 matrix values */
#define MPC7_LAMBDA_U_ADDR 361        /*lambda_u: 7x5 matrix values */
#define MPC7_LAMBDA_X_ADDR 396        /*lambda_x: 14x6 matrix values */
#define MPC7_LAMBDA_ZT_ADDR 480        /*lambda_zt: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_ADDR 552        /*lambda_alpha_t: 6x6 matrix values */
#define MPC7_G_ADDR 588        /*g: 14x20 matrix values */
#define MPC7_Q_Y_ADDR 868        /*Q_y: 6x6 matrix values */
#define MPC7_R_Q_PP_ADDR 904        /*R_q_pp: 7x7 matrix values */
#define MPC7_Q_Y_P_REF_ADDR 953        /*Q_y_p_ref: 6x6 matrix values */
#define MPC7_Q_Y_REF_ADDR 989        /*Q_y_ref: 6x6 matrix values */
#define MPC7_EPSILON_ADDR 1025        /*epsilon: [1 1] array values */
#define MPC7_EPSILON_ADDR 1026        /*epsilon: [1 1] array values */
#define MPC7_X_MIN_ADDR 1027        /*x_min: [14 1] array values */
#define MPC7_X_MAX_ADDR 1041        /*x_max: [14 1] array values */
#define MPC7_U_MIN_ADDR 1055        /*u_min: [7 1] array values */
#define MPC7_U_MAX_ADDR 1062        /*u_max: [7 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC7_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(14x1), zt_0(12x1), y_d(6x6), y_d_p(6x6), y_d_pp(6x6)] */
#define MPC7_IN_INIT_GUESS_ADDR 134        /* init_guess = [u(7x5), x(14x6), zt(12x6), alpha_t(6x6), lambda_u(7x5), lambda_x(14x6), lambda_zt(12x6), lambda_alpha_t(6x6), g(14x20)] */
#define MPC7_IN_PARAM_WEIGHT_ADDR 746        /* param_weight = [Q_y(6x6), R_q_pp(7x7), Q_y_p_ref(6x6), Q_y_ref(6x6), epsilon(1x1), epsilon(1x1), x_min(14x1), x_max(14x1), u_min(7x1), u_max(7x1)] */

// OUTPUT DIMENSIONS:
#define MPC7_U_OPT_LEN 7        /*u_opt: [7 1] array values */
#define MPC7_U_OUT_LEN 35        /*u_out: 7x5 matrix values */
#define MPC7_X_OUT_LEN 84        /*x_out: 14x6 matrix values */
#define MPC7_ZT_OUT_LEN 72        /*zt_out: 12x6 matrix values */
#define MPC7_ALPHA_T_OUT_LEN 36        /*alpha_t_out: 6x6 matrix values */
#define MPC7_LAMBDA_U_OUT_LEN 35        /*lambda_u_out: 7x5 matrix values */
#define MPC7_LAMBDA_X_OUT_LEN 84        /*lambda_x_out: 14x6 matrix values */
#define MPC7_LAMBDA_ZT_OUT_LEN 72        /*lambda_zt_out: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_OUT_LEN 36        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC7_G_OUT_LEN 280        /*g_out: 14x20 matrix values */
#define MPC7_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC7_JT_YY_REF_LEN 1        /*Jt_yy_ref: [1 1] array values */
#define MPC7_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC7_JR_YY_REF_LEN 1        /*Jr_yy_ref: [1 1] array values */
#define MPC7_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC7_U_OPT_ADDR 947        /*u_opt: [7 1] array values */
#define MPC7_U_OUT_ADDR 954        /*u_out: 7x5 matrix values */
#define MPC7_X_OUT_ADDR 989        /*x_out: 14x6 matrix values */
#define MPC7_ZT_OUT_ADDR 1073        /*zt_out: 12x6 matrix values */
#define MPC7_ALPHA_T_OUT_ADDR 1145        /*alpha_t_out: 6x6 matrix values */
#define MPC7_LAMBDA_U_OUT_ADDR 1181        /*lambda_u_out: 7x5 matrix values */
#define MPC7_LAMBDA_X_OUT_ADDR 1216        /*lambda_x_out: 14x6 matrix values */
#define MPC7_LAMBDA_ZT_OUT_ADDR 1300        /*lambda_zt_out: 12x6 matrix values */
#define MPC7_LAMBDA_ALPHA_T_OUT_ADDR 1372        /*lambda_alpha_t_out: 6x6 matrix values */
#define MPC7_G_OUT_ADDR 1408        /*g_out: 14x20 matrix values */
#define MPC7_J_YT_ADDR 1688        /*J_yt: [1 1] array values */
#define MPC7_JT_YY_REF_ADDR 1689        /*Jt_yy_ref: [1 1] array values */
#define MPC7_J_YR_ADDR 1690        /*J_yr: [1 1] array values */
#define MPC7_JR_YY_REF_ADDR 1691        /*Jr_yy_ref: [1 1] array values */
#define MPC7_J_Q_PP_ADDR 1692        /*J_q_pp: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC7_OUT_U_OPT_ADDR 947        /* u_opt = [u[0:6](7x1)] */
#define MPC7_OUT_INIT_GUESS_OUT_ADDR 954        /* init_guess_out = [u_out(7x5), x_out(14x6), zt_out(12x6), alpha_t_out(6x6), lambda_u_out(7x5), lambda_x_out(14x6), lambda_zt_out(12x6), lambda_alpha_t_out(6x6), g_out(14x20)] */
#define MPC7_OUT_COST_FUN_1_ADDR 1566        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC7_OUT_COST_FUN_2_ADDR 1567        /* cost_fun_2 = [Jt_yy_ref(1x1)] */
#define MPC7_OUT_COST_FUN_3_ADDR 1568        /* cost_fun_3 = [J_yr(1x1)] */
#define MPC7_OUT_COST_FUN_4_ADDR 1569        /* cost_fun_4 = [Jr_yy_ref(1x1)] */
#define MPC7_OUT_COST_FUN_5_ADDR 1570        /* cost_fun_5 = [J_q_pp(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
