/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC8_alloc_mem(void);
int MPC8_init_mem(int mem);
void MPC8_free_mem(int mem);
int MPC8_checkout(void);
void MPC8_release(int mem);
void MPC8_incref(void);
void MPC8_decref(void);
casadi_int MPC8_n_in(void);
casadi_int MPC8_n_out(void);
casadi_real MPC8_default_in(casadi_int i);
const char* MPC8_name_in(casadi_int i);
const char* MPC8_name_out(casadi_int i);
const casadi_int* MPC8_sparsity_in(casadi_int i);
const casadi_int* MPC8_sparsity_out(casadi_int i);
int MPC8_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC8_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC8_SZ_ARG 23
#define MPC8_SZ_RES 17
#define MPC8_SZ_IW 3740
#define MPC8_SZ_W 59828
#ifdef __cplusplus
} /* extern "C" */
#endif
