/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int MPC9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MPC9_alloc_mem(void);
int MPC9_init_mem(int mem);
void MPC9_free_mem(int mem);
int MPC9_checkout(void);
void MPC9_release(int mem);
void MPC9_incref(void);
void MPC9_decref(void);
casadi_int MPC9_n_in(void);
casadi_int MPC9_n_out(void);
casadi_real MPC9_default_in(casadi_int i);
const char* MPC9_name_in(casadi_int i);
const char* MPC9_name_out(casadi_int i);
const casadi_int* MPC9_sparsity_in(casadi_int i);
const casadi_int* MPC9_sparsity_out(casadi_int i);
int MPC9_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MPC9_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MPC9_SZ_ARG 23
#define MPC9_SZ_RES 18
#define MPC9_SZ_IW 410
#define MPC9_SZ_W 4171
#ifdef __cplusplus
} /* extern "C" */
#endif
