/* Automatically generated by MATLAB (generate_mpc_config_typedef.m) */
/* Do not edit this file. To regenerate, run "mpc_casdadi_main.m" with "generate_realtime_udp_c_fun=true" */

#ifndef MPC_CONFIG_H
#define MPC_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include "casadi_types.h"

typedef struct {
    const casadi_real dt;
    const casadi_uint kinematic_mpc;
    const char* x0_init_path;
    const char* init_guess_path;
    const char* traj_data_path;
    const casadi_uint traj_data_per_horizon;
    const casadi_uint traj_data_real_len;
    const casadi_uint* traj_indices;
    casadi_uint y_d_len;
    casadi_uint init_guess_len;
    casadi_uint x_k_addr;
    casadi_uint y_d_addr;
    casadi_uint in_init_guess_addr;
    casadi_uint out_init_guess_addr;
    casadi_uint in_param_weight_addr;
    const casadi_real* param_weight;
    casadi_uint param_weight_len;
    CasadiFunPtr_t casadi_fun;
    const casadi_real** arg;
    casadi_real** res;
    casadi_int* iw;
    casadi_real* w;
    const casadi_uint* arg_indices;
    const casadi_uint* res_indices;
    casadi_uint arg_in_len;
    casadi_uint res_out_len;
    casadi_uint u_opt_len;
    casadi_uint w_end_addr;
    casadi_uint u_opt_addr;
    int mem;
} mpc_config_t;

#ifdef __cplusplus
}
#endif

#endif // MPC_CONFIG_H
