/* Automatically generated by MATLAB (generate_mpc_config_typedef.m) */
/* Do not edit this file. To regenerate, run "mpc_casdadi_main.m" with "generate_realtime_udp_c_fun=true" */

#ifndef MPC_CONFIG_H
#define MPC_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include "casadi_types.h"

typedef struct {
    const casadi_uint x_k_addr;
    const casadi_uint x_k_len;
    const casadi_uint t_k_addr;
    const casadi_uint t_k_len;
    const casadi_uint zt_k_addr;
    const casadi_uint zt_k_len;
    const casadi_uint y_d_addr;
    const casadi_uint y_d_len;
    const casadi_uint y_d_p_addr;
    const casadi_uint y_d_p_len;
    const casadi_uint y_d_pp_addr;
    const casadi_uint y_d_pp_len;
    const casadi_uint x_prev_addr;
    const casadi_uint x_prev_len;
    const casadi_uint z_prev_addr;
    const casadi_uint z_prev_len;
    const casadi_uint alpha_prev_addr;
    const casadi_uint alpha_prev_len;
    const casadi_uint theta_prev_addr;
    const casadi_uint theta_prev_len;
    const casadi_uint traj_select_addr;
    const casadi_uint traj_select_len;
    const casadi_uint u_addr;
    const casadi_uint u_len;
    const casadi_uint v_addr;
    const casadi_uint v_len;
    const casadi_uint x_addr;
    const casadi_uint x_len;
    const casadi_uint zt_addr;
    const casadi_uint zt_len;
    const casadi_uint alpha_t_addr;
    const casadi_uint alpha_t_len;
    const casadi_uint theta_addr;
    const casadi_uint theta_len;
    const casadi_uint lambda_u_addr;
    const casadi_uint lambda_u_len;
    const casadi_uint lambda_v_addr;
    const casadi_uint lambda_v_len;
    const casadi_uint lambda_x_addr;
    const casadi_uint lambda_x_len;
    const casadi_uint lambda_zt_addr;
    const casadi_uint lambda_zt_len;
    const casadi_uint lambda_alpha_t_addr;
    const casadi_uint lambda_alpha_t_len;
    const casadi_uint lambda_theta_addr;
    const casadi_uint lambda_theta_len;
    const casadi_uint g_addr;
    const casadi_uint g_len;
    const casadi_uint Q_y_addr;
    const casadi_uint Q_y_len;
    const casadi_uint Q_yN_addr;
    const casadi_uint Q_yN_len;
    const casadi_uint epsilon_t_addr;
    const casadi_uint epsilon_t_len;
    const casadi_uint epsilon_r_addr;
    const casadi_uint epsilon_r_len;
    const casadi_uint Q_y_ref_addr;
    const casadi_uint Q_y_ref_len;
    const casadi_uint Q_y_p_ref_addr;
    const casadi_uint Q_y_p_ref_len;
    const casadi_uint Q_theta_addr;
    const casadi_uint Q_theta_len;
    const casadi_uint Q_thetaN_addr;
    const casadi_uint Q_thetaN_len;
    const casadi_uint R_q_ref_addr;
    const casadi_uint R_q_ref_len;
    const casadi_uint R_q_p_addr;
    const casadi_uint R_q_p_len;
    const casadi_uint R_u_addr;
    const casadi_uint R_u_len;
    const casadi_uint R_v_addr;
    const casadi_uint R_v_len;
    const casadi_uint R_x_prev_addr;
    const casadi_uint R_x_prev_len;
    const casadi_uint R_z_prev_addr;
    const casadi_uint R_z_prev_len;
    const casadi_uint R_alpha_prev_addr;
    const casadi_uint R_alpha_prev_len;
    const casadi_uint R_theta_prev_addr;
    const casadi_uint R_theta_prev_len;
    const casadi_uint lambda_u_ew_addr;
    const casadi_uint lambda_u_ew_len;
    const casadi_uint q_ref_addr;
    const casadi_uint q_ref_len;
    const casadi_uint x_min_addr;
    const casadi_uint x_min_len;
    const casadi_uint x_max_addr;
    const casadi_uint x_max_len;
    const casadi_uint u_min_addr;
    const casadi_uint u_min_len;
    const casadi_uint u_max_addr;
    const casadi_uint u_max_len;
    const casadi_uint v_min_addr;
    const casadi_uint v_min_len;
    const casadi_uint v_max_addr;
    const casadi_uint v_max_len;
    const casadi_uint reference_values_addr;
    const casadi_uint reference_values_len;
    const casadi_uint init_guess_addr;
    const casadi_uint init_guess_len;
    const casadi_uint param_weight_addr;
    const casadi_uint param_weight_len;
} mpc_input_config_t;

typedef struct {
    const casadi_real dt;
    const casadi_uint kinematic_mpc;
    const char* x0_init_path;
    const char* init_guess_path;
    const char* traj_data_path;
    const casadi_uint traj_data_per_horizon;
    const casadi_uint traj_data_real_len;
    const casadi_uint* traj_indices;
    casadi_uint y_d_len;
    casadi_uint init_guess_len;
    casadi_uint x_k_addr;
    casadi_uint y_d_addr;
    casadi_uint in_init_guess_addr;
    casadi_uint out_init_guess_addr;
    casadi_uint in_param_weight_addr;
    const casadi_real* param_weight;
    casadi_uint param_weight_len;
    CasadiFunPtr_t casadi_fun;
    const casadi_real** arg;
    casadi_real** res;
    casadi_int* iw;
    casadi_real* w;
    const casadi_uint* arg_indices;
    const casadi_uint* res_indices;
    casadi_uint arg_in_len;
    casadi_uint res_out_len;
    casadi_uint u_opt_len;
    casadi_uint w_end_addr;
    casadi_uint u_opt_addr;
    int mem;
    const mpc_input_config_t input_config;
} mpc_config_t;

#ifdef __cplusplus
}
#endif

#endif // MPC_CONFIG_H
