/* Automatically generated by MATLAB (generate_mpc_config_typedef.m) */
/* Do not edit this file. To regenerate, run "mpc_casdadi_main.m" with "generate_realtime_udp_c_fun=true" */

#ifndef MPC_CONFIG_H
#define MPC_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "casadi_types.h"

typedef struct {
    const char* x0_init_path;
    const char* init_guess_path;
    const char* traj_data_path;
    const uint32_t traj_data_per_horizon;
    const uint32_t traj_data_real_len;
    const uint32_t* traj_indices;
    uint32_t y_d_len;
    uint32_t init_guess_len;
    uint32_t x_k_addr;
    uint32_t y_d_addr;
    uint32_t in_init_guess_addr;
    uint32_t in_param_weight_addr;
    const casadi_real* param_weight;
    uint32_t param_weight_len;
    CasadiFunPtr_t casadi_fun;
    const casadi_real** arg;
    casadi_real** res;
    casadi_int* iw;
    casadi_real* w;
    casadi_real* u_opt;
    const uint32_t* arg_indices;
    const uint32_t* res_indices;
    uint32_t arg_in_len;
    uint32_t res_out_len;
    uint32_t u_opt_len;
    uint32_t w_end_addr;
    uint32_t u_opt_addr;
    int mem;
} mpc_config_t;

#ifdef __cplusplus
}
#endif

#endif // MPC_CONFIG_H
