/* Automatically generated by MATLAB (generate_param_robot_header.m) */
/* Do not edit this file. To regenerate, run "mpc_casdadi_main.m" with "generate_realtime_udp_c_fun=true" */

#include "param_robot.h"

const casadi_real PARAM_ROBOT_Q_0_REF[PARAM_ROBOT_N_DOF] = {0,-7.853982e-01,0,-2.356194e+00,0,1.570796e+00,7.853982e-01};
const casadi_real PARAM_ROBOT_Q_0_P_REF[PARAM_ROBOT_N_DOF] = {0,0,0,0,0,0,0};
const casadi_real PARAM_ROBOT_Q_0_PP_REF[PARAM_ROBOT_N_DOF] = {0,0,0,0,0,0,0};
const casadi_real PARAM_ROBOT_G[3] = {0,0,9.810000e+00};
const casadi_real PARAM_ROBOT_G_VIS[3] = {0,0,-9.810000e+00};
const casadi_real PARAM_ROBOT_Q_LIMIT_UPPER[PARAM_ROBOT_N_DOF] = {2.309300e+00,1.513300e+00,2.493700e+00,-4.461000e-01,2.480000e+00,4.209400e+00,2.689500e+00};
const casadi_real PARAM_ROBOT_Q_LIMIT_LOWER[PARAM_ROBOT_N_DOF] = {-2.309300e+00,-1.513300e+00,-2.493700e+00,-2.747800e+00,-2.480000e+00,8.521000e-01,-2.689500e+00};
const casadi_real PARAM_ROBOT_Q_P_LIMIT_UPPER[PARAM_ROBOT_N_DOF] = {2,1,1.500000e+00,1.250000e+00,3,1.500000e+00,3};
const casadi_real PARAM_ROBOT_Q_P_LIMIT_LOWER[PARAM_ROBOT_N_DOF] = {-2,-1,-1.500000e+00,-1.250000e+00,-3,-1.500000e+00,-3};
const casadi_real PARAM_ROBOT_Q_PP_LIMIT_UPPER[PARAM_ROBOT_N_DOF] = {10,10,10,10,10,10,10};
const casadi_real PARAM_ROBOT_Q_PP_LIMIT_LOWER[PARAM_ROBOT_N_DOF] = {-10,-10,-10,-10,-10,-10,-10};
const casadi_real PARAM_ROBOT_Q_N[PARAM_ROBOT_N_DOF] = {0,0,0,-1.596950e+00,0,2.530750e+00,0};
const casadi_real PARAM_ROBOT_TORQUE_LIMIT_UPPER[PARAM_ROBOT_N_DOF] = {87,87,87,87,12,12,12};
const casadi_real PARAM_ROBOT_TORQUE_LIMIT_LOWER[PARAM_ROBOT_N_DOF] = {-87,-87,-87,-87,-12,-12,-12};
const casadi_real PARAM_ROBOT_P_0[3] = {0,0,0};
const casadi_real PARAM_ROBOT_R_0[9] = {1,0,0,0,1,0,0,0,1};
const casadi_real PARAM_ROBOT_SUGIHARA_LIMB_VECTOR[PARAM_ROBOT_N_DOF] = {1.108890e-01,9.985600e-02,6.806250e-03,1.474560e-01,7.744000e-03,1.144900e-02,1.069156e-02};
const casadi_uint PARAM_ROBOT_YT_INDICES[3] = {0,1,2};
const casadi_uint PARAM_ROBOT_YR_INDICES[3] = {0,1,2};
const casadi_uint PARAM_ROBOT_N_INDICES_FIXED[PARAM_ROBOT_N_FIXED] = {2};
const casadi_uint PARAM_ROBOT_N_X_INDICES_FIXED[2*PARAM_ROBOT_N_FIXED] = {2,9};
const casadi_uint PARAM_ROBOT_N_INDICES[PARAM_ROBOT_N_RED] = {0,1,3,4,5,6};
const casadi_uint PARAM_ROBOT_N_X_INDICES[2*PARAM_ROBOT_N_RED] = {0,1,3,4,5,6,7,8,10,11,12,13};


// Function to get the robot config
robot_config_t get_robot_config()
{
   static robot_config_t Config = {
       .nq = PARAM_ROBOT_N_DOF,
       .nx = 2*PARAM_ROBOT_N_DOF,
       .nq_red = PARAM_ROBOT_N_RED,
       .nx_red = 2*PARAM_ROBOT_N_RED,
       .nq_fixed = PARAM_ROBOT_N_FIXED,
       .n_indices = PARAM_ROBOT_N_INDICES,
       .n_x_indices = PARAM_ROBOT_N_X_INDICES,
       .n_indices_fixed = PARAM_ROBOT_N_INDICES_FIXED,
       .n_x_indices_fixed = PARAM_ROBOT_N_X_INDICES_FIXED,
       .yt_indices = PARAM_ROBOT_YT_INDICES,
       .yr_indices = PARAM_ROBOT_YR_INDICES,
       .q_0_ref = PARAM_ROBOT_Q_0_REF,
       .q_0_p_ref = PARAM_ROBOT_Q_0_P_REF,
       .q_0_pp_ref = PARAM_ROBOT_Q_0_PP_REF,
       .q_limit_upper = PARAM_ROBOT_Q_LIMIT_UPPER,
       .q_limit_lower = PARAM_ROBOT_Q_LIMIT_LOWER,
       .q_p_limit_upper = PARAM_ROBOT_Q_P_LIMIT_UPPER,
       .q_p_limit_lower = PARAM_ROBOT_Q_P_LIMIT_LOWER,
       .q_pp_limit_upper = PARAM_ROBOT_Q_PP_LIMIT_UPPER,
       .q_pp_limit_lower = PARAM_ROBOT_Q_PP_LIMIT_LOWER,
       .q_n = PARAM_ROBOT_Q_N,
       .torque_limit_upper = PARAM_ROBOT_TORQUE_LIMIT_UPPER,
       .torque_limit_lower = PARAM_ROBOT_TORQUE_LIMIT_LOWER,
       .sugihara_limb_vector = PARAM_ROBOT_SUGIHARA_LIMB_VECTOR,
       .traj_data_path = TRAJ_DATA_PATH,
       .x0_init_path = X0_INIT_PATH, // Default path to init configuration of trajectories
       .traj_data_real_len = TRAJ_DATA_REAL_LEN, // Real length of trajectory data (without last prediction horizon)
   };
   return Config;
}

