/* Automatically generated by MATLAB (generate_param_robot_header.m) */
/* Do not edit this file. To regenerate, run "mpc_casdadi_main.m" with "generate_realtime_udp_c_fun=true" */

#ifndef PARAM_ROBOT_PARAM_H
#define PARAM_ROBOT_PARAM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "casadi_types.h"

#define PARAM_ROBOT_N_DOF 7
#define PARAM_ROBOT_N_RED 6
#define PARAM_ROBOT_N_FIXED 1
#define PARAM_ROBOT_M_T 3
#define PARAM_ROBOT_M_R 3
#define PARAM_ROBOT_M 6
extern const casadi_real PARAM_ROBOT_Q_0_REF[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_0_P_REF[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_0_PP_REF[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_G[3];
#define PARAM_ROBOT_G_X 0
#define PARAM_ROBOT_G_Y 0
#define PARAM_ROBOT_G_Z 9.81
extern const casadi_real PARAM_ROBOT_G_VIS[3];
extern const casadi_real PARAM_ROBOT_Q_LIMIT_UPPER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_LIMIT_LOWER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_P_LIMIT_UPPER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_P_LIMIT_LOWER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_PP_LIMIT_UPPER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_PP_LIMIT_LOWER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_Q_N[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_TORQUE_LIMIT_UPPER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_TORQUE_LIMIT_LOWER[PARAM_ROBOT_N_DOF];
extern const casadi_real PARAM_ROBOT_P_0[3];
extern const casadi_real PARAM_ROBOT_R_0[9];
#define PARAM_ROBOT_SP0_X -0.041018
#define PARAM_ROBOT_SP0_Y -0.00014
#define PARAM_ROBOT_SP0_Z 0.049974
#define PARAM_ROBOT_M0 0.629769
#define PARAM_ROBOT_I0_XX 0.00315
#define PARAM_ROBOT_I0_XY 8.2904e-07
#define PARAM_ROBOT_I0_XZ 0.00015
#define PARAM_ROBOT_I0_YY 0.00388
#define PARAM_ROBOT_I0_YZ 8.2299e-06
#define PARAM_ROBOT_I0_ZZ 0.004285
#define PARAM_ROBOT_L1 0.333
#define PARAM_ROBOT_SP1_X 0.003875
#define PARAM_ROBOT_SP1_Y 0.002081
#define PARAM_ROBOT_SP1_Z -0.04762
#define PARAM_ROBOT_M1 4.97068
#define PARAM_ROBOT_I1_XX 0.70337
#define PARAM_ROBOT_I1_XY -0.000139
#define PARAM_ROBOT_I1_XZ 0.006772
#define PARAM_ROBOT_I1_YY 0.70661
#define PARAM_ROBOT_I1_YZ 0.019169
#define PARAM_ROBOT_I1_ZZ 0.009117
#define PARAM_ROBOT_L2 0.316
#define PARAM_ROBOT_SP2_X -0.003141
#define PARAM_ROBOT_SP2_Y -0.02872
#define PARAM_ROBOT_SP2_Z 0.003495
#define PARAM_ROBOT_M2 0.646926
#define PARAM_ROBOT_I2_XX 0.007962
#define PARAM_ROBOT_I2_XY -0.003925
#define PARAM_ROBOT_I2_XZ 0.010254
#define PARAM_ROBOT_I2_YY 0.02811
#define PARAM_ROBOT_I2_YZ 0.000704
#define PARAM_ROBOT_I2_ZZ 0.025995
#define PARAM_ROBOT_L3 0.0825
#define PARAM_ROBOT_SP3_X 0.027518
#define PARAM_ROBOT_SP3_Y 0.039252
#define PARAM_ROBOT_SP3_Z -0.066502
#define PARAM_ROBOT_M3 3.2286
#define PARAM_ROBOT_I3_XX 0.037242
#define PARAM_ROBOT_I3_XY -0.004761
#define PARAM_ROBOT_I3_XZ -0.011396
#define PARAM_ROBOT_I3_YY 0.036155
#define PARAM_ROBOT_I3_YZ -0.012805
#define PARAM_ROBOT_I3_ZZ 0.01083
#define PARAM_ROBOT_L4 0.384
#define PARAM_ROBOT_SP4_X -0.05317
#define PARAM_ROBOT_SP4_Y 0.104419
#define PARAM_ROBOT_SP4_Z 0.027454
#define PARAM_ROBOT_M4 3.5879
#define PARAM_ROBOT_I4_XX 0.025853
#define PARAM_ROBOT_I4_XY 0.007796
#define PARAM_ROBOT_I4_XZ -0.001332
#define PARAM_ROBOT_I4_YY 0.019552
#define PARAM_ROBOT_I4_YZ 0.008641
#define PARAM_ROBOT_I4_ZZ 0.028323
#define PARAM_ROBOT_L5 0.088
#define PARAM_ROBOT_SP5_X -0.011953
#define PARAM_ROBOT_SP5_Y 0.041065
#define PARAM_ROBOT_SP5_Z -0.038437
#define PARAM_ROBOT_M5 1.22595
#define PARAM_ROBOT_I5_XX 0.035549
#define PARAM_ROBOT_I5_XY -0.002117
#define PARAM_ROBOT_I5_XZ -0.004037
#define PARAM_ROBOT_I5_YY 0.029474
#define PARAM_ROBOT_I5_YZ 0.000229
#define PARAM_ROBOT_I5_ZZ 0.008627
#define PARAM_ROBOT_L6 0.107
#define PARAM_ROBOT_SP6_X 0.060149
#define PARAM_ROBOT_SP6_Y -0.014117
#define PARAM_ROBOT_SP6_Z -0.010517
#define PARAM_ROBOT_M6 1.66656
#define PARAM_ROBOT_I6_XX 0.001964
#define PARAM_ROBOT_I6_XY 0.000109
#define PARAM_ROBOT_I6_XZ -0.001158
#define PARAM_ROBOT_I6_YY 0.004354
#define PARAM_ROBOT_I6_YZ 0.000341
#define PARAM_ROBOT_I6_ZZ 0.005433
#define PARAM_ROBOT_L7 0.1034
#define PARAM_ROBOT_SP7_X 0.010517
#define PARAM_ROBOT_SP7_Y -0.004252
#define PARAM_ROBOT_SP7_Z 0.061597
#define PARAM_ROBOT_M7 0.735522
#define PARAM_ROBOT_I7_XX 0.012516
#define PARAM_ROBOT_I7_XY -0.000428
#define PARAM_ROBOT_I7_XZ -0.001196
#define PARAM_ROBOT_I7_YY 0.010027
#define PARAM_ROBOT_I7_YZ -0.000741
#define PARAM_ROBOT_I7_ZZ 0.004815
#define PARAM_ROBOT_SP8_X 0
#define PARAM_ROBOT_SP8_Y 0
#define PARAM_ROBOT_SP8_Z 0
#define PARAM_ROBOT_M8 1e-05
#define PARAM_ROBOT_I8_XX 1e-06
#define PARAM_ROBOT_I8_XY 0
#define PARAM_ROBOT_I8_XZ 0
#define PARAM_ROBOT_I8_YY 1e-06
#define PARAM_ROBOT_I8_YZ 0
#define PARAM_ROBOT_I8_ZZ 1e-06
#define PARAM_ROBOT_SP9_X -0.01
#define PARAM_ROBOT_SP9_Y 0
#define PARAM_ROBOT_SP9_Z 0.03
#define PARAM_ROBOT_M9 0.73
#define PARAM_ROBOT_I9_XX 0.001
#define PARAM_ROBOT_I9_XY 0
#define PARAM_ROBOT_I9_XZ 0
#define PARAM_ROBOT_I9_YY 0.0025
#define PARAM_ROBOT_I9_YZ 0
#define PARAM_ROBOT_I9_ZZ 0.0017
#define PARAM_ROBOT_W_FINGER 0
#define PARAM_ROBOT_L_FINGER 0.0584
#define PARAM_ROBOT_SP_FINGER_X 0
#define PARAM_ROBOT_SP_FINGER_Y 0
#define PARAM_ROBOT_SP_FINGER_Z 0
#define PARAM_ROBOT_M_FINGER 0.015
#define PARAM_ROBOT_I_FINGER_XX 2.375e-06
#define PARAM_ROBOT_I_FINGER_XY 0
#define PARAM_ROBOT_I_FINGER_XZ 0
#define PARAM_ROBOT_I_FINGER_YY 2.375e-06
#define PARAM_ROBOT_I_FINGER_YZ 0
#define PARAM_ROBOT_I_FINGER_ZZ 7.5e-07
extern const casadi_real PARAM_ROBOT_SUGIHARA_LIMB_VECTOR[PARAM_ROBOT_N_DOF];
extern const casadi_uint PARAM_ROBOT_YT_INDICES[3];
extern const casadi_uint PARAM_ROBOT_YR_INDICES[3];
extern const casadi_uint PARAM_ROBOT_N_INDICES_FIXED[PARAM_ROBOT_N_FIXED];
extern const casadi_uint PARAM_ROBOT_N_X_INDICES_FIXED[2*PARAM_ROBOT_N_FIXED];
extern const casadi_uint PARAM_ROBOT_N_INDICES[PARAM_ROBOT_N_RED];
extern const casadi_uint PARAM_ROBOT_N_X_INDICES[2*PARAM_ROBOT_N_RED];

typedef struct {
    const casadi_uint n_dof;
    const casadi_uint n_red;
    const casadi_uint* n_indices;
    const casadi_uint* n_x_indices;
    const casadi_uint* n_indices_fixed;
    const casadi_uint* n_x_indices_fixed;
    const casadi_uint* yt_indices;
    const casadi_uint* yr_indices;
    const casadi_real* q_0_ref;
    const casadi_real* q_0_p_ref;
    const casadi_real* q_0_pp_ref;
    const casadi_real* q_limit_upper;
    const casadi_real* q_limit_lower;
    const casadi_real* q_p_limit_upper;
    const casadi_real* q_p_limit_lower;
    const casadi_real* q_pp_limit_upper;
    const casadi_real* q_pp_limit_lower;
    const casadi_real* q_n;
    const casadi_real* torque_limit_upper;
    const casadi_real* torque_limit_lower;
    const casadi_real* sugihara_limb_vector;
} robot_config_t;

robot_config_t get_robot_config();


#ifdef __cplusplus
}
#endif

#endif /* PARAM_ROBOT_PARAM_H */
