/* MPC8_adressdef.h */
/* Automatically generated by MATLAB (generate_realtime_udp_c_fun.m) */

#ifndef MPC8_ADRESSDEF_H
#define MPC8_ADRESSDEF_H

#define MPC01_IW_LEN 870
#define MPC01_ARG_LEN 23
#define MPC01_RES_LEN 17
#define MPC01_W_LEN 28609
static const uint32_t MPC01_ARG[] = {0,54,330};
static const uint32_t MPC01_RES[] = {474,480,756,757,758,759,760};
#define MPC01_W_END_ADDRESS 761

// INPUT DIMENSIONS:
#define MPC01_X_K_LEN 12        /*x_k: [12 1] array values */
#define MPC01_Y_D_LEN 42        /*y_d: 7x6 matrix values */
#define MPC01_U_LEN 30        /*u: 6x5 matrix values */
#define MPC01_X_LEN 72        /*x: 12x6 matrix values */
#define MPC01_LAMBDA_U_LEN 30        /*lambda_u: 6x5 matrix values */
#define MPC01_LAMBDA_X_LEN 72        /*lambda_x: 12x6 matrix values */
#define MPC01_G_LEN 72        /*g: 12x6 matrix values */
#define MPC01_Q_Y_LEN 36        /*Q_y: 6x6 matrix values */
#define MPC01_Q_YN_LEN 36        /*Q_yN: 6x6 matrix values */
#define MPC01_R_Q_PP_LEN 36        /*R_q_pp: 6x6 matrix values */
#define MPC01_X_MIN_LEN 12        /*x_min: [12 1] array values */
#define MPC01_X_MAX_LEN 12        /*x_max: [12 1] array values */
#define MPC01_U_MIN_LEN 6        /*u_min: [6 1] array values */
#define MPC01_U_MAX_LEN 6        /*u_max: [6 1] array values */

#define MPC01_REFERENCE_VALUES_LEN 54        /* reference_values = [x_k(12x1), y_d(7x6)] */
#define MPC01_INIT_GUESS_LEN 276        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define MPC01_PARAM_WEIGHT_LEN 144        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(6x6), x_min(12x1), x_max(12x1), u_min(6x1), u_max(6x1)] */

// INPUT ADDRESSES:
#define MPC01_X_K_ADDR 0        /*x_k: [12 1] array values */
#define MPC01_Y_D_ADDR 12        /*y_d: 7x6 matrix values */
#define MPC01_U_ADDR 54        /*u: 6x5 matrix values */
#define MPC01_X_ADDR 84        /*x: 12x6 matrix values */
#define MPC01_LAMBDA_U_ADDR 156        /*lambda_u: 6x5 matrix values */
#define MPC01_LAMBDA_X_ADDR 186        /*lambda_x: 12x6 matrix values */
#define MPC01_G_ADDR 258        /*g: 12x6 matrix values */
#define MPC01_Q_Y_ADDR 330        /*Q_y: 6x6 matrix values */
#define MPC01_Q_YN_ADDR 366        /*Q_yN: 6x6 matrix values */
#define MPC01_R_Q_PP_ADDR 402        /*R_q_pp: 6x6 matrix values */
#define MPC01_X_MIN_ADDR 438        /*x_min: [12 1] array values */
#define MPC01_X_MAX_ADDR 450        /*x_max: [12 1] array values */
#define MPC01_U_MIN_ADDR 462        /*u_min: [6 1] array values */
#define MPC01_U_MAX_ADDR 468        /*u_max: [6 1] array values */

// CASADI FUN INPUT ADRESSES:
#define MPC01_IN_REFERENCE_VALUES_ADDR 0        /* reference_values = [x_k(12x1), y_d(7x6)] */
#define MPC01_IN_INIT_GUESS_ADDR 54        /* init_guess = [u(6x5), x(12x6), lambda_u(6x5), lambda_x(12x6), g(12x6)] */
#define MPC01_IN_PARAM_WEIGHT_ADDR 330        /* param_weight = [Q_y(6x6), Q_yN(6x6), R_q_pp(6x6), x_min(12x1), x_max(12x1), u_min(6x1), u_max(6x1)] */

// OUTPUT DIMENSIONS:
#define MPC01_U_OPT_LEN 6        /*u_opt: [6 1] array values */
#define MPC01_U_OUT_LEN 30        /*u_out: 6x5 matrix values */
#define MPC01_X_OUT_LEN 72        /*x_out: 12x6 matrix values */
#define MPC01_LAMBDA_U_OUT_LEN 30        /*lambda_u_out: 6x5 matrix values */
#define MPC01_LAMBDA_X_OUT_LEN 72        /*lambda_x_out: 12x6 matrix values */
#define MPC01_G_OUT_LEN 72        /*g_out: 12x6 matrix values */
#define MPC01_J_YT_LEN 1        /*J_yt: [1 1] array values */
#define MPC01_J_YR_LEN 1        /*J_yr: [1 1] array values */
#define MPC01_J_YT_N_LEN 1        /*J_yt_N: [1 1] array values */
#define MPC01_J_YR_N_LEN 1        /*J_yr_N: [1 1] array values */
#define MPC01_J_Q_PP_LEN 1        /*J_q_pp: [1 1] array values */

// OUTPUT ADDRESSES:
#define MPC01_U_OPT_ADDR 474        /*u_opt: [6 1] array values */
#define MPC01_U_OUT_ADDR 480        /*u_out: 6x5 matrix values */
#define MPC01_X_OUT_ADDR 510        /*x_out: 12x6 matrix values */
#define MPC01_LAMBDA_U_OUT_ADDR 582        /*lambda_u_out: 6x5 matrix values */
#define MPC01_LAMBDA_X_OUT_ADDR 612        /*lambda_x_out: 12x6 matrix values */
#define MPC01_G_OUT_ADDR 684        /*g_out: 12x6 matrix values */
#define MPC01_J_YT_ADDR 756        /*J_yt: [1 1] array values */
#define MPC01_J_YR_ADDR 757        /*J_yr: [1 1] array values */
#define MPC01_J_YT_N_ADDR 758        /*J_yt_N: [1 1] array values */
#define MPC01_J_YR_N_ADDR 759        /*J_yr_N: [1 1] array values */
#define MPC01_J_Q_PP_ADDR 760        /*J_q_pp: [1 1] array values */

// CASADI FUN OUTPUT ADRESSES:
#define MPC01_OUT_U_OPT_ADDR 474        /* u_opt = [u[0:5](6x1)] */
#define MPC01_OUT_INIT_GUESS_OUT_ADDR 480        /* init_guess_out = [u_out(6x5), x_out(12x6), lambda_u_out(6x5), lambda_x_out(12x6), g_out(12x6)] */
#define MPC01_OUT_COST_FUN_1_ADDR 756        /* cost_fun_1 = [J_yt(1x1)] */
#define MPC01_OUT_COST_FUN_2_ADDR 757        /* cost_fun_2 = [J_yr(1x1)] */
#define MPC01_OUT_COST_FUN_3_ADDR 758        /* cost_fun_3 = [J_yt_N(1x1)] */
#define MPC01_OUT_COST_FUN_4_ADDR 759        /* cost_fun_4 = [J_yr_N(1x1)] */
#define MPC01_OUT_COST_FUN_5_ADDR 760        /* cost_fun_5 = [J_q_pp(1x1)] */

#endif /* MPC8_ADRESSDEF_H */
