if(~exist('parameter_str', 'var'))
    parameters_7dof;
end

steps = 10;

% Extract the data for each trajectory
traj_indices = [1, 2, 4, 5];
for traj_idx = traj_indices
    % Extract the data
    time_data = param_traj_data.t(1:steps:10000)';
    p_d_data = param_traj_data.p_d(:,1:steps:10000,traj_idx)';
    q_d_data = param_traj_data.q_d(:,1:steps:10000,traj_idx)';
    
    % Create tables with appropriate column names
    p_d_table = array2table([time_data, p_d_data], 'VariableNames', {'time', 'x', 'y', 'z'});
    q_d_table = array2table([time_data, q_d_data], 'VariableNames', {'time', 'quat1', 'quat2', 'quat3', 'quat4'});
    
    % Save the data as CSV files
    writetable(p_d_table, sprintf('/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter4/p_d_data_traj%d.csv', traj_idx));
    writetable(q_d_table, sprintf('/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter4/q_d_data_traj%d.csv', traj_idx));
end

% TRAJ 1 ID Damping

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj1/ID_damping/robot_plots_20250415_094713.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj1_ID_damping.csv', ...
    steps ...
    );

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj1/ID_damping_Simulation/robot_plots_20250422_110845.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj1_ID_damping_simulation.csv', ...
    steps ...
    );

% TRAJ 1 ID ThresholdSmallSingularValues

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj1/ID_ThresholdSmallSingularValues/robot_plots_20250415_101140.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj1_ID_ThresholdSmallSingularValues.csv', ...
    steps ...
);

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj1/ID_ThresholdSmallSingularValues_Simulation/robot_plots_20250422_110939.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj1_ID_ThresholdSmallSingularValues_simulation.csv', ...
    steps ...
);

% TRAJ 1 Crocoddyl NMPC 20 N step 1

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250425/traj1/Crocoddyl_N_step_1_N_MPC_20_yr1e5/robot_plots_20250428_161907.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj1_Crocoddyl_NMPC_20_N_step_1.csv', ...
    steps ...
);

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj1/Crocoddyl_NMPC_20_N_step_1_Simulation/robot_plots_20250422_111307.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj1_Crocoddyl_NMPC_20_N_step_1_simulation.csv', ...
    steps ...
);

% TRAJ 2 ID Damping

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj2/ID_damping/robot_plots_20250425_103626.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj2_ID_damping.csv', ...
    steps ...
    );

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj2/ID_damping_Simulation/robot_plots_20250422_112103.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj2_ID_damping_simulation.csv', ...
    steps ...
    );

% TRAJ 2 ID ThresholdSmallSingularValues

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj2/ID_ThresholdSmallSingularValues_202020/robot_plots_20250425_103656.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj2_ID_ThresholdSmallSingularValues.csv', ...
    steps ...
);

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj2/ID_ThresholdSmallSingularValues_Simulation/robot_plots_20250422_112143.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj2_ID_ThresholdSmallSingularValues_simulation.csv', ...
    steps ...
);

% TRAJ 2 Crocoddyl NMPC 20 N step 1

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250425/traj2/Crocoddyl_N_step_1_N_MPC_20_yr1e5_q_x_bound2e0/robot_plots_20250428_162033.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj2_Crocoddyl_NMPC_20_N_step_1.csv', ...
    steps ...
);

export_selected_columns( ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/2DOF_Manipulator/messungen/250309/Traj2/Crocoddyl_NMPC_20_N_step_1_Simulation/robot_plots_20250422_112014.csv', ...
    '/media/daten/Projekte/Studium/Master/Masterarbeit_SS2024/thesis_latex/Master-Thesis-2024-25/doc/tex/figures/chapter5/Traj2_Crocoddyl_NMPC_20_N_step_1_simulation.csv', ...
    steps ...
);

function export_selected_columns(input_csv, output_csv, steps)
    data = readtable(input_csv, 'VariableNamingRule', 'preserve');
    exportTable = table();
    exportTable.time = data.("t (s)")(1:steps:end);
    exportTable.e_x = 1e3*data.("e_x (m)")(1:steps:end);
    exportTable.e_y = 1e3*data.("e_y (m)")(1:steps:end);
    exportTable.e_z = 1e3*data.("e_z (m)")(1:steps:end);
    exportTable.quat_err_2 = data.("quat_err_2")(1:steps:end);
    exportTable.quat_err_3 = data.("quat_err_3")(1:steps:end);
    exportTable.quat_err_4 = data.("quat_err_4")(1:steps:end);
    exportTable.manip = data.("Manip. w = √( det( JJ⸆ ) )")(1:steps:end);
    exportTable.qd_1 = data.("q̇_1")(1:steps:end);
    exportTable.qd_2 = data.("q̇_2")(1:steps:end);
    exportTable.qd_3 = data.("q̇_3")(1:steps:end);
    exportTable.qd_4 = data.("q̇_4")(1:steps:end);
    exportTable.qd_5 = data.("q̇_5")(1:steps:end);
    exportTable.qd_6 = data.("q̇_6")(1:steps:end);
    exportTable.qd_7 = data.("q̇_7")(1:steps:end);
    exportTable.tau_1 = data.("tau_1")(1:steps:end);
    exportTable.tau_2 = data.("tau_2")(1:steps:end);
    exportTable.tau_3 = data.("tau_3")(1:steps:end);
    exportTable.tau_4 = data.("tau_4")(1:steps:end);
    exportTable.tau_5 = data.("tau_5")(1:steps:end);
    exportTable.tau_6 = data.("tau_6")(1:steps:end);
    exportTable.tau_7 = data.("tau_7")(1:steps:end);
    writetable(exportTable, output_csv);
end