/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

int robot_model_bus_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int robot_model_bus_fun_alloc_mem(void);
int robot_model_bus_fun_init_mem(int mem);
void robot_model_bus_fun_free_mem(int mem);
int robot_model_bus_fun_checkout(void);
void robot_model_bus_fun_release(int mem);
void robot_model_bus_fun_incref(void);
void robot_model_bus_fun_decref(void);
casadi_int robot_model_bus_fun_n_in(void);
casadi_int robot_model_bus_fun_n_out(void);
casadi_real robot_model_bus_fun_default_in(casadi_int i);
const char* robot_model_bus_fun_name_in(casadi_int i);
const char* robot_model_bus_fun_name_out(casadi_int i);
const casadi_int* robot_model_bus_fun_sparsity_in(casadi_int i);
const casadi_int* robot_model_bus_fun_sparsity_out(casadi_int i);
int robot_model_bus_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int robot_model_bus_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define robot_model_bus_fun_SZ_ARG 2
#define robot_model_bus_fun_SZ_RES 6
#define robot_model_bus_fun_SZ_IW 0
#define robot_model_bus_fun_SZ_W 172
#ifdef __cplusplus
} /* extern "C" */
#endif
